import fs from 'node:fs'
import test from 'node:test'
import assert from 'node:assert/strict'
import { createD1 } from './helpers/d1-adapter.mjs'
import { executeCommand, executeRead } from '../../src/service.js'

const migration=fs.readFileSync(new URL('../../migrations/0001_initial.sql',import.meta.url),'utf8')
function setup(){return{DB:createD1(migration),SHARE_TOKEN_SECRET:'share-secret-that-is-longer-than-thirty-two',MEDIA_SIGNING_SECRET:'media-secret-that-is-longer-than-thirty-two'}}
const bird=(gender,ringNumber)=>({species:'测试鹦鹉',ringNumber,gender,birthDate:'2025-01-01',priceCents:100000,publicIntro:'公开',privateNotes:'内部',media:[]})

test('D1 schema and command receipts enforce idempotent unique rings',async()=>{const env=setup();try{const first=await executeCommand(env,'owner','parrots.create',bird('MALE','r- 001'),'create:1');const repeated=await executeCommand(env,'owner','parrots.create',bird('MALE','r- 001'),'create:1');assert.equal(repeated.id,first.id);await assert.rejects(executeCommand(env,'owner','parrots.create',bird('MALE','R-001'),'create:2'),error=>error.code==='DUPLICATE_RING');const rows=await env.DB.prepare('SELECT COUNT(*) AS count FROM parrots').first();assert.equal(rows.count,1)}finally{env.DB.close()}})

test('command receipts reject reusing a request id for another action',async()=>{const env=setup();try{await executeCommand(env,'owner','parrots.create',bird('MALE','RECEIPT-1'),'receipt:reuse');await assert.rejects(executeCommand(env,'owner','parrots.setBreeder',{id:'missing',revision:1},'receipt:reuse'),error=>error.code==='CONFLICT')}finally{env.DB.close()}})

test('auto-pair hatching and completion restore both parents atomically',async()=>{const env=setup();try{const male=await executeCommand(env,'owner','parrots.create',bird('MALE','M-1'),'create:m'),female=await executeCommand(env,'owner','parrots.create',bird('FEMALE','F-1'),'create:f');const mb=await executeCommand(env,'owner','parrots.setBreeder',{id:male.id,revision:1},'breeder:m'),fb=await executeCommand(env,'owner','parrots.setBreeder',{id:female.id,revision:1},'breeder:f');const hatch=await executeCommand(env,'owner','hatching.create',{maleId:male.id,femaleId:female.id,maleRevision:mb.revision,femaleRevision:fb.revision,species:'测试鹦鹉',startDate:'2026-07-18',eggs:3},'hatch:create');let rows=await env.DB.prepare('SELECT status FROM parrots ORDER BY id').all();assert.deepEqual(rows.results.map(row=>row.status),['INCUBATING','INCUBATING']);await executeCommand(env,'owner','hatching.complete',{id:hatch.id,revision:hatch.revision},'hatch:complete');rows=await env.DB.prepare('SELECT status,active_pair_id FROM parrots').all();assert.equal(rows.results.every(row=>row.status==='BREEDER'&&row.active_pair_id===null),true)}finally{env.DB.close()}})

test('active breeding list exposes camelCase relations for the miniapp',async()=>{const env=setup();try{const male=await executeCommand(env,'owner','parrots.create',bird('MALE','M-2'),'create:m2'),female=await executeCommand(env,'owner','parrots.create',bird('FEMALE','F-2'),'create:f2');const mb=await executeCommand(env,'owner','parrots.setBreeder',{id:male.id,revision:1},'breeder:m2'),fb=await executeCommand(env,'owner','parrots.setBreeder',{id:female.id,revision:1},'breeder:f2');const pair=await executeCommand(env,'owner','breeding.pair',{maleId:male.id,femaleId:female.id,maleRevision:mb.revision,femaleRevision:fb.revision},'pair:m2');const active=await executeRead(env,'owner','breeding.listActive',{},'https://api.example.com','');assert.equal(active[0].maleId,male.id);assert.equal(active[0].femaleId,female.id);assert.equal(typeof active[0].pairedAt,'string');assert.equal('paired_at' in active[0],false);assert.equal(active[0].revision,pair.revision)}finally{env.DB.close()}})

test('paired parrots may update media without changing gender',async()=>{const env=setup();try{const male=await executeCommand(env,'owner','parrots.create',bird('MALE','M-3'),'create:m3'),female=await executeCommand(env,'owner','parrots.create',bird('FEMALE','F-3'),'create:f3');const mb=await executeCommand(env,'owner','parrots.setBreeder',{id:male.id,revision:1},'breeder:m3'),fb=await executeCommand(env,'owner','parrots.setBreeder',{id:female.id,revision:1},'breeder:f3');await executeCommand(env,'owner','breeding.pair',{maleId:male.id,femaleId:female.id,maleRevision:mb.revision,femaleRevision:fb.revision},'pair:m3');const now=new Date().toISOString();await env.DB.prepare('INSERT INTO media_assets (id,owner_open_id,type,size,file_name,object_key,upload_id,mime,source,status,revision,created_at,updated_at,deleted_at,deleted_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind('asset-m3','owner','image',1024,'m3.jpg','private/owner/m3.jpg',null,'image/jpeg','LOCAL_UPLOAD','COMMITTED',1,now,now,null,null).run();const current=await env.DB.prepare('SELECT revision FROM parrots WHERE id=?').bind(male.id).first();const updated=await executeCommand(env,'owner','parrots.update',{id:male.id,revision:current.revision,updates:{gender:'MALE',media:[{assetId:'asset-m3',type:'image'}]}},'update:m3-media');assert.equal(updated.revision,current.revision+1);const saved=await env.DB.prepare('SELECT gender,media_json FROM parrots WHERE id=?').bind(male.id).first();assert.equal(saved.gender,'MALE');assert.match(saved.media_json,/asset-m3/);await assert.rejects(executeCommand(env,'owner','parrots.update',{id:male.id,revision:updated.revision,updates:{gender:'FEMALE'}},'update:m3-gender'),error=>error.code==='INVALID_STATE')}finally{env.DB.close()}})

test('sale return removes revenue and produces terminal returned state',async()=>{const env=setup();try{const created=await executeCommand(env,'owner','parrots.create',bird('FEMALE','SALE-1'),'create:sale'),sale=await executeCommand(env,'owner','sales.create',{parrotId:created.id,parrotRevision:1,buyer:'张先生',buyerContact:'13800000000',saleDate:'2026-07-18',priceCents:120000},'sale:create');let dashboard=await executeRead(env,'owner','dashboard.get',{},'https://api.example.com','');assert.equal(dashboard.stats.revenueCents,120000);await executeCommand(env,'owner','sales.return',{id:sale.id,revision:sale.revision,reason:'健康复检未通过'},'sale:return');dashboard=await executeRead(env,'owner','dashboard.get',{},'https://api.example.com','');assert.equal(dashboard.stats.revenueCents,0);assert.equal(dashboard.stats.returnRate,100);assert.equal(dashboard.stats.returned,1)}finally{env.DB.close()}})

test('deletions physically remove parrot data and share tokens',async()=>{const env=setup();try{const birdRecord=await executeCommand(env,'owner','parrots.create',bird('MALE','DELETE-1'),'delete:create'),share=await executeCommand(env,'owner','shares.create',{parrotId:birdRecord.id},'delete:share');await executeCommand(env,'owner','shares.revoke',{token:share.token},'delete:share-revoke');let row=await env.DB.prepare('SELECT COUNT(*) AS count FROM share_tokens').first();assert.equal(row.count,0);await executeCommand(env,'owner','sales.create',{parrotId:birdRecord.id,parrotRevision:birdRecord.revision,buyer:'测试买家',buyerContact:'',saleDate:'2026-07-19',priceCents:100000},'delete:sale');await executeCommand(env,'owner','parrots.delete',{id:birdRecord.id,revision:2},'delete:parrot');for(const table of ['parrots','sales_records','share_tokens','breeding_pairs','hatching_records']){row=await env.DB.prepare(`SELECT COUNT(*) AS count FROM ${table}`).first();assert.equal(row.count,0,table)}}finally{env.DB.close()}})

test('removing a completed hatching record physically removes its row',async()=>{const env=setup();try{const male=await executeCommand(env,'owner','parrots.create',bird('MALE','HARD-HATCH-M'),'hard-hatch:create-m'),female=await executeCommand(env,'owner','parrots.create',bird('FEMALE','HARD-HATCH-F'),'hard-hatch:create-f'),maleBreeder=await executeCommand(env,'owner','parrots.setBreeder',{id:male.id,revision:1},'hard-hatch:breeder-m'),femaleBreeder=await executeCommand(env,'owner','parrots.setBreeder',{id:female.id,revision:1},'hard-hatch:breeder-f'),hatching=await executeCommand(env,'owner','hatching.create',{maleId:male.id,femaleId:female.id,maleRevision:maleBreeder.revision,femaleRevision:femaleBreeder.revision,species:'测试鹦鹉',startDate:'2026-07-19',eggs:2},'hard-hatch:create'),completed=await executeCommand(env,'owner','hatching.complete',{id:hatching.id,revision:hatching.revision},'hard-hatch:complete');await executeCommand(env,'owner','hatching.delete',{id:hatching.id,revision:completed.revision},'hard-hatch:delete');const row=await env.DB.prepare('SELECT COUNT(*) AS count FROM hatching_records WHERE id=?').bind(hatching.id).first();assert.equal(row.count,0)}finally{env.DB.close()}})

test('sync.snapshot aggregates all datasets in a single read',async()=>{const env=setup();try{const created=await executeCommand(env,'owner','parrots.create',bird('MALE','SNAP-1'),'create:snap');const snapshot=await executeRead(env,'owner','sync.snapshot',{},'https://api.example.com','');assert.equal(snapshot.parrots.items.length,1);assert.equal(snapshot.parrots.items[0].id,created.id);assert.deepEqual(snapshot.pairs,[]);assert.equal(snapshot.hatching.items.length,0);assert.equal(snapshot.sales.items.length,0);assert.equal(snapshot.dashboard.stats.total,1)}finally{env.DB.close()}})
