import { ApiError, STATUS, WRITE_ACTIONS, dateOnly, deriveShareToken, ensure, id, integer, json, normalizeRing, nowIso, parseJson, sha256, text } from './core.js'
import { all, auditStatement, first, mediaItems, owned, revisionCheck, rowMedia, serializeParrot, snapshot, statement } from './db.js'
import { r2AbortMultipartUpload as cosAbortMultipartUpload, r2DeleteObject as cosDeleteObject } from './r2.js'
import { generateSaleCopy } from './sale-copy.js'

const GENDERS = new Set(['MALE','FEMALE','UNKNOWN'])
const FOLLOW_UP = new Set(['WAITING','VISITED','UNREACHABLE'])
const FEEDING_TYPES = new Set(['FORMULA','MIXED','SOLID'])

function validateFeedingPlan(input) {
  const ageFromMonths=integer(input.ageFromMonths,'起始月龄（月）',0,240),ageFromDays=integer(input.ageFromDays,'起始月龄（天）',0,30),ageToMonths=integer(input.ageToMonths,'结束月龄（月）',0,240),ageToDays=integer(input.ageToDays,'结束月龄（天）',0,30),temperatureMin=integer(input.temperatureMin,'最低水温',0,100),temperatureMax=integer(input.temperatureMax,'最高水温',temperatureMin,100)
  ensure(ageToMonths * 31 + ageToDays >= ageFromMonths * 31 + ageFromDays,'VALIDATION_ERROR','结束年龄不能小于起始年龄')
  const feedingType=input.feedingType || 'FORMULA'
  ensure(FEEDING_TYPES.has(feedingType),'VALIDATION_ERROR','食物方案类型无效')
  return {name:text(input.name,'方案名称',80),species:text(input.species,'适用品种',60),stage:text(input.stage,'生长阶段',40),ageFromMonths,ageFromDays,ageToMonths,ageToDays,formulaName:text(input.formulaName,'奶粉名称',100,false),waterMl:integer(input.waterMl,'水量',0,1000),powderScoops:text(input.powderScoops,'奶粉勺数',40,false),temperatureMin,temperatureMax,feedingsPerDay:integer(input.feedingsPerDay,'每日次数',0,24),amountMl:text(input.amountMl,'单次参考量',60,false),feedingMethod:text(input.feedingMethod,'喂养方式',40,false),temperatureCheck:text(input.temperatureCheck,'水温判断',500,false),preparationNotes:text(input.preparationNotes,'冲泡说明',1000,false),feedingNotes:text(input.feedingNotes,'喂养注意事项',1500,false),fullnessNotes:text(input.fullnessNotes,'喂饱判断',1000,false),warningNotes:text(input.warningNotes,'异常提醒',1000,false),feedingType,seedFoodName:text(input.seedFoodName,'谷子或固体食物',100,false),seedFoodAmount:text(input.seedFoodAmount,'谷子或固体食物用量',100,false),seedFoodNotes:text(input.seedFoodNotes,'谷子或固体食物说明',1000,false)}
}

function feedingPlanView(row) { return {id:row.id,name:row.name,species:row.species,stage:row.stage,ageFromMonths:Number(row.age_from_months),ageFromDays:Number(row.age_from_days || 0),ageToMonths:Number(row.age_to_months),ageToDays:Number(row.age_to_days || 0),isEnabled:Boolean(row.is_enabled),formulaName:row.formula_name,waterMl:Number(row.water_ml),powderScoops:row.powder_scoops,temperatureMin:Number(row.temperature_min),temperatureMax:Number(row.temperature_max),feedingsPerDay:Number(row.feedings_per_day),amountMl:row.amount_ml,feedingMethod:row.feeding_method,temperatureCheck:row.temperature_check,preparationNotes:row.preparation_notes,feedingNotes:row.feeding_notes,fullnessNotes:row.fullness_notes,warningNotes:row.warning_notes,feedingType:row.feeding_type || 'FORMULA',seedFoodName:row.seed_food_name || '',seedFoodAmount:row.seed_food_amount || '',seedFoodNotes:row.seed_food_notes || '',revision:Number(row.revision),updatedAt:row.updated_at} }

function validateSupply(input) {
  const category = input.category
  ensure(category === 'SUPPLY' || category === 'MEDICINE', 'VALIDATION_ERROR', '耗材分类无效')
  const purchaseDate = dateOnly(input.purchaseDate, '购买时间')
  const today = new Date(Date.now() + 28800000).toISOString().slice(0, 10)
  ensure(purchaseDate <= today, 'VALIDATION_ERROR', '购买时间不能晚于今天')
  return { category, name: text(input.name, '名称', 100), amountCents: integer(input.amountCents, '金额', 1, 99999999900), weight: text(input.weight, '重量', 60, false), purchaseDate, notes: text(input.notes, '备注', 1000, false) }
}

function supplyView(row) { return { id: row.id, category: row.category, name: row.name, amountCents: Number(row.amount_cents), weight: row.weight || '', purchaseDate: row.purchase_date, notes: row.notes || '', createdAt: row.created_at } }

function validateParrot(input, partial = false) {
  const result = {}; const has = key => Object.prototype.hasOwnProperty.call(input || {}, key)
  if (!partial || has('breed')) result.breed = text(input.breed,'品种',60)
  if (!partial || has('species')) result.species = text(input.species,'名称',60)
  if (!partial || has('ringNumber')) { result.ringNumber=text(input.ringNumber,'脚环',40,false); result.ringNumberNormalized=normalizeRing(result.ringNumber); if(result.ringNumber)ensure(result.ringNumberNormalized,'VALIDATION_ERROR','脚环无效') }
  if (!partial || has('gender')) { ensure(GENDERS.has(input.gender),'VALIDATION_ERROR','性别无效'); result.gender=input.gender }
  if (!partial || has('birthDate')) { result.birthDate=dateOnly(input.birthDate,'出生日期'); const sh=new Date(Date.now()+28800000); const today=`${sh.getUTCFullYear()}-${String(sh.getUTCMonth()+1).padStart(2,'0')}-${String(sh.getUTCDate()).padStart(2,'0')}`; ensure(result.birthDate<=today,'VALIDATION_ERROR','出生日期不能晚于今天') }
  if (!partial || has('priceCents')) result.priceCents=integer(input.priceCents,'价格',0,99999999900)
  if (!partial || has('publicIntro')) result.publicIntro=text(input.publicIntro,'公开介绍',1000,false)
  if (!partial || has('privateNotes')) result.privateNotes=text(input.privateNotes,'内部备注',3000,false)
  if (!partial || has('media')) { ensure(Array.isArray(input.media)&&input.media.length<=20,'VALIDATION_ERROR','媒体数量无效'); result.media=input.media.map(item=>({assetId:text(item.assetId,'媒体标识',80),type:item.type})) }
  return result
}

function validatePurchaseDate(input) {
  const purchaseDate = dateOnly(input.purchaseDate, '购买日期')
  const sh = new Date(Date.now() + 28800000)
  const today = `${sh.getUTCFullYear()}-${String(sh.getUTCMonth() + 1).padStart(2, '0')}-${String(sh.getUTCDate()).padStart(2, '0')}`
  ensure(purchaseDate <= today, 'VALIDATION_ERROR', '购买日期不能晚于今天')
  return purchaseDate
}

function validateParent(input, label, partial = false) {
  if (input == null || input === '') return partial ? undefined : null
  ensure(input && typeof input === 'object', 'VALIDATION_ERROR', `${label}信息无效`)
  const source = input.source
  ensure(source === 'LIBRARY' || source === 'MANUAL', 'VALIDATION_ERROR', `${label}来源无效`)
  if (source === 'LIBRARY') return { source, id: text(input.id, `${label}档案`, 80) }
  return { source, species: text(input.species, `${label}品种`, 60), ringNumber: text(input.ringNumber, `${label}脚环`, 40, false) }
}

async function isDescendant(env, owner, candidateId, birdId) {
  const pending = [candidateId], seen = new Set()
  while (pending.length) {
    const current = pending.pop()
    if (!current || seen.has(current)) continue
    if (current === birdId) return true
    seen.add(current)
    ensure(seen.size <= 32, 'VALIDATION_ERROR', '血统关系层级异常')
    const row = await first(env, 'SELECT father_id,mother_id FROM parrots WHERE id=? AND owner_open_id=?', current, owner)
    if (row) pending.push(row.father_id, row.mother_id)
  }
  return false
}

async function resolveParent(env, owner, input, expectedGender, label, birdId) {
  if (!input) return null
  if (input.source === 'MANUAL') return { source: 'MANUAL', id: null, species: input.species, ringNumber: input.ringNumber || '' }
  ensure(input.id !== birdId, 'VALIDATION_ERROR', `${label}不能选择本鸟`)
  const parent = await owned(env, 'parrots', input.id, owner)
  ensure(parent.gender === expectedGender, 'VALIDATION_ERROR', `${label}必须选择${expectedGender === 'MALE' ? '公鸟' : '母鸟'}`)
  ensure(!(await isDescendant(env, owner, parent.id, birdId)), 'VALIDATION_ERROR', '不能形成循环血统')
  return { source: 'LIBRARY', id: parent.id, species: parent.species, ringNumber: parent.ring_number }
}

function validateOffspringGroups(input, hatched) {
  if (input == null) return undefined
  ensure(Array.isArray(input) && input.length <= 20, 'VALIDATION_ERROR', '出窝品种明细无效')
  const names = new Set(); const groups = input.map(item => {
    const species = text(item && item.species, '出窝品种', 60)
    ensure(!names.has(species), 'VALIDATION_ERROR', '同一品种只能填写一次'); names.add(species)
    return { species, count: integer(item && item.count, '出窝数量', 1, 100) }
  })
  ensure(groups.reduce((sum, item) => sum + item.count, 0) <= hatched, 'VALIDATION_ERROR', '品种数量不能超过出壳数量')
  return groups
}

function validateClutchChicks(input, expectedCount) {
  ensure(Array.isArray(input) && input.length === expectedCount, 'VALIDATION_ERROR', `请完整录入本窝${expectedCount}只幼鸟`)
  const rings = new Set()
  return input.map((item, index) => {
    const breed = text(item && item.breed, `第${index + 1}只幼鸟品种`, 60)
    const species = text(item && item.species, `第${index + 1}只幼鸟名称`, 60)
    const ringNumber = text(item && item.ringNumber, `第${index + 1}只幼鸟脚环`, 40, false)
    const normalized = normalizeRing(ringNumber)
    ensure(!normalized || !rings.has(normalized), 'VALIDATION_ERROR', '同一窝幼鸟的脚环不能重复')
    if (normalized) rings.add(normalized)
    ensure(GENDERS.has(item && item.gender), 'VALIDATION_ERROR', `第${index + 1}只幼鸟性别无效`)
    return { breed, species, ringNumber, ringNumberNormalized: normalized, gender: item.gender, priceCents: integer(item && item.priceCents, `第${index + 1}只幼鸟估值`, 0, 99999999900), privateNotes: text(item && item.privateNotes, `第${index + 1}只幼鸟备注`, 3000, false) }
  })
}

async function validateMedia(env, owner, items) {
  const output=[]; const seen=new Set()
  for(const item of items||[]){ ensure(['image','video'].includes(item.type),'VALIDATION_ERROR','媒体类型无效'); ensure(!seen.has(item.assetId),'VALIDATION_ERROR','媒体不能重复'); seen.add(item.assetId); const asset=await first(env,'SELECT * FROM media_assets WHERE id=? AND owner_open_id=? AND status=? AND deleted_at IS NULL',item.assetId,owner,'COMMITTED'); ensure(asset&&asset.type===item.type,'VALIDATION_ERROR','媒体尚未完成上传'); output.push({assetId:asset.id,type:asset.type,key:asset.object_key}) }
  return output
}

async function receipt(env, owner, requestId) { return first(env,'SELECT * FROM command_receipts WHERE receipt_id=?',await sha256(`${owner}:${requestId}`)) }
function receiptResult(row) { return parseJson(row.result_json,{}) }

async function saveBatch(env, owner, action, requestId, statements, result) {
  const receiptId=await sha256(`${owner}:${requestId}`)
  statements.push(statement(env,'INSERT INTO command_receipts (receipt_id,owner_open_id,request_id,action,result_json,created_at) VALUES (?,?,?,?,?,?)',receiptId,owner,requestId,action,json(action==='shares.create'?{parrotId:result.parrotId,expiresAt:result.expiresAt}:result),nowIso()))
  try { await env.DB.batch(statements) } catch(error) { const message=String(error&&error.message||''); if(['parrots.create','parrots.update'].includes(action)&&/unique|parrots_owner_ring/i.test(message)) throw new ApiError('DUPLICATE_RING','脚环已存在',409); throw error }
  return result
}

export async function executeCommand(env, owner, action, input, requestId, actorOpenId = null) {
  ensure(WRITE_ACTIONS.has(action),'NOT_FOUND','接口不存在',404); text(requestId,'requestId',100)
  const existing=await receipt(env,owner,requestId)
  if(existing){ ensure(existing.action===action,'CONFLICT','请求号已用于其他操作',409); const stored=receiptResult(existing); if(action==='shares.create') return {...stored,token:await deriveShareToken(owner,requestId,env.SHARE_TOKEN_SECRET)}; return stored }
  const result=await commandHandlers[action](env,owner,input||{},requestId,actorOpenId)
  const data=await saveBatch(env,owner,action,requestId,result.statements,result.data)
  await purgeReleasedMedia(env,owner,result.releasedAssetIds)
  return data
}

const RECYCLE_WINDOW_MS = 15 * 86400000

async function parrotPurgeStatements(env, owner, bird, requestId) {
  const sales=await all(env,'SELECT media_json FROM sales_records WHERE owner_open_id=? AND parrot_id=?',owner,bird.id)
  const releasedAssetIds=[...mediaIds(rowMedia(bird)),...sales.flatMap(row=>mediaIds(rowMedia(row)))]
  return { releasedAssetIds, statements:[statement(env,'DELETE FROM sale_copy_documents WHERE owner_open_id=? AND parrot_id=?',owner,bird.id),statement(env,'DELETE FROM share_tokens WHERE owner_open_id=? AND parrot_id=?',owner,bird.id),statement(env,'DELETE FROM hatching_records WHERE owner_open_id=? AND (male_id=? OR female_id=?)',owner,bird.id,bird.id),statement(env,'DELETE FROM breeding_pairs WHERE owner_open_id=? AND (male_id=? OR female_id=?)',owner,bird.id,bird.id),statement(env,'DELETE FROM sales_records WHERE owner_open_id=? AND parrot_id=?',owner,bird.id),statement(env,'DELETE FROM parrots WHERE id=? AND owner_open_id=?',bird.id,owner),auditStatement(env,owner,'parrots.purge','parrot',bird.id,requestId,bird,{purged:true,deletedAt:bird.deleted_at})] }
}

export async function purgeExpiredParrots(env) {
  const cutoff=new Date(Date.now()-RECYCLE_WINDOW_MS).toISOString()
  const rows=await all(env,'SELECT * FROM parrots WHERE deleted_at IS NOT NULL AND deleted_at<=? ORDER BY deleted_at ASC LIMIT 100',cutoff)
  for(const bird of rows){
    const purge=await parrotPurgeStatements(env,bird.owner_open_id,bird,`scheduled-purge:${bird.id}:${bird.deleted_at}`)
    await env.DB.batch(purge.statements)
    await purgeReleasedMedia(env,bird.owner_open_id,purge.releasedAssetIds)
  }
  return rows.length
}

function mediaIds(items){ return [...new Set((items||[]).map(item=>item&&item.assetId).filter(Boolean))] }
function removedMediaIds(before,after){ const next=new Set(mediaIds(after)); return mediaIds(before).filter(assetId=>!next.has(assetId)) }
async function purgeReleasedMedia(env,owner,assetIds=[]){
  for(const assetId of new Set(assetIds)){
    const asset=await first(env,'SELECT * FROM media_assets WHERE id=? AND owner_open_id=?',assetId,owner)
    if(!asset)continue
    const referenced=await first(env,"SELECT 1 AS found FROM parrots,json_each(parrots.media_json) WHERE parrots.owner_open_id=? AND json_extract(json_each.value,'$.assetId')=? UNION ALL SELECT 1 AS found FROM sales_records,json_each(sales_records.media_json) WHERE sales_records.owner_open_id=? AND json_extract(json_each.value,'$.assetId')=? LIMIT 1",owner,assetId,owner,assetId)
    if(referenced)continue
    try{
      if(asset.status==='PENDING'&&asset.upload_id)await cosAbortMultipartUpload(env,asset.object_key,asset.upload_id)
      else await cosDeleteObject(env,asset.object_key)
      await env.DB.prepare('DELETE FROM media_assets WHERE id=? AND owner_open_id=?').bind(assetId,owner).run()
    }catch(error){ console.error('[media purge]',assetId,error) }
  }
}

async function simpleStatus(env,owner,input,requestId,from,to,action){ const bird=await owned(env,'parrots',text(input.id,'id',80),owner); revisionCheck(bird,input.revision); ensure(bird.status===from,'INVALID_STATE','当前状态不允许执行该操作'); const now=nowIso(),next={...bird,status:to,revision:bird.revision+1,updated_at:now}; return {data:{id:bird.id,revision:next.revision},statements:[statement(env,'UPDATE parrots SET status=?,revision=?,updated_at=? WHERE id=?',to,next.revision,now,bird.id),auditStatement(env,owner,action,'parrot',bird.id,requestId,bird,next)]} }

async function closePair(env,owner,pair,reason,requestId,now){ const male=await owned(env,'parrots',pair.male_id,owner),female=await owned(env,'parrots',pair.female_id,owner); if(reason==='HATCHING_CANCELLED'||reason==='HATCHING_COMPLETED')return [statement(env,'UPDATE breeding_pairs SET status=?,revision=revision+1,updated_at=? WHERE id=?','ACTIVE',now,pair.id),statement(env,'UPDATE parrots SET status=?,active_pair_id=?,revision=revision+1,updated_at=? WHERE id IN (?,?)',STATUS.PAIRED,pair.id,now,male.id,female.id),auditStatement(env,owner,'hatching.resumePair','breedingPair',pair.id,requestId,pair,{status:'ACTIVE',hatching:reason})]; return [statement(env,'UPDATE breeding_pairs SET status=?,ended_at=?,end_reason=?,revision=revision+1,updated_at=? WHERE id=?','CLOSED',now,reason,now,pair.id),statement(env,'UPDATE parrots SET status=?,active_pair_id=NULL,paired_at=NULL,revision=revision+1,updated_at=? WHERE id IN (?,?)',STATUS.BREEDER,now,male.id,female.id),auditStatement(env,owner,`breeding.${reason.toLowerCase()}`,'breedingPair',pair.id,requestId,pair,{status:'CLOSED',endReason:reason})] }

async function createParrot(env, owner, input, requestId, source) {
  const value = validateParrot(input), media = await validateMedia(env, owner, value.media), now = nowIso(), birdId = id()
  const father = await resolveParent(env, owner, validateParent(input.father, '父鸟'), 'MALE', '父鸟', birdId), mother = await resolveParent(env, owner, validateParent(input.mother, '母鸟'), 'FEMALE', '母鸟', birdId)
  ensure(!(father && mother && father.source === 'LIBRARY' && mother.source === 'LIBRARY' && father.id === mother.id), 'VALIDATION_ERROR', '父鸟和母鸟不能为同一只鸟')
  const purchaseDate = source === 'INTRODUCTION' ? validatePurchaseDate(input) : null
  const data = { id: birdId, owner_open_id: owner, breed: value.breed, species: value.species, ring_number: value.ringNumber, ring_number_normalized: value.ringNumberNormalized, gender: value.gender, status: STATUS.FOR_SALE, birth_date: value.birthDate, price_cents: value.priceCents, public_intro: value.publicIntro, private_notes: value.privateNotes, media_json: json(media), father_id: father && father.id, mother_id: mother && mother.id, father_snapshot_json: json(father), mother_snapshot_json: json(mother), active_pair_id: null, paired_at: null, revision: 1, created_at: now, updated_at: now, deleted_at: null, deleted_by: null, record_source: source, purchase_date: purchaseDate, introduction_stage: source === 'INTRODUCTION' ? 'GROWING' : null }
  return { data: { id: birdId, revision: 1 }, statements: [statement(env, 'INSERT INTO parrots (id,owner_open_id,breed,species,ring_number,ring_number_normalized,gender,status,birth_date,price_cents,public_intro,private_notes,media_json,father_id,mother_id,father_snapshot_json,mother_snapshot_json,active_pair_id,paired_at,revision,created_at,updated_at,deleted_at,deleted_by,record_source,purchase_date,introduction_stage) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)', ...Object.values(data)), auditStatement(env, owner, source === 'INTRODUCTION' ? 'introductions.create' : 'parrots.create', 'parrot', birdId, requestId, null, data)] }
}

const commandHandlers={
  'parrots.create':async(env,owner,input,requestId)=>createParrot(env,owner,input,requestId,'PROFILE'),
  'introductions.create':async(env,owner,input,requestId)=>createParrot(env,owner,input,requestId,'INTRODUCTION'),
  'introductions.markForSale':async(env,owner,input,requestId)=>{ const bird=await owned(env,'parrots',text(input.id,'id',80),owner); revisionCheck(bird,input.revision); ensure(bird.record_source==='INTRODUCTION'&&bird.status===STATUS.FOR_SALE&&bird.introduction_stage==='GROWING','INVALID_STATE','当前引种鸟不能转为待售'); const now=nowIso(),next={...bird,introduction_stage:'FOR_SALE',revision:bird.revision+1,updated_at:now}; return {data:{id:bird.id,revision:next.revision},statements:[statement(env,'UPDATE parrots SET introduction_stage=?,revision=?,updated_at=? WHERE id=?',next.introduction_stage,next.revision,now,bird.id),auditStatement(env,owner,'introductions.markForSale','parrot',bird.id,requestId,bird,next)]} },
  'parrots.createFromClutch':async(env,owner,input,requestId)=>createFromClutch(env,owner,input,requestId),
  'parrots.update':async(env,owner,input,requestId)=>{ const bird=await owned(env,'parrots',text(input.id,'id',80),owner); revisionCheck(bird,input.revision); const value=validateParrot(input.updates||{},true),hasFather=Object.prototype.hasOwnProperty.call(input.updates||{},'father'),hasMother=Object.prototype.hasOwnProperty.call(input.updates||{},'mother'),hasPurchaseDate=Object.prototype.hasOwnProperty.call(input.updates||{},'purchaseDate'); ensure(Object.keys(value).length||hasFather||hasMother||hasPurchaseDate,'VALIDATION_ERROR','没有可更新的字段'); ensure(!hasPurchaseDate||bird.record_source==='INTRODUCTION','VALIDATION_ERROR','只有引种鸟可以修改购买日期'); if(value.gender&&value.gender!==bird.gender&&bird.active_pair_id)throw new ApiError('INVALID_STATE','活动配对期间不能修改性别'); const media=value.media?await validateMedia(env,owner,value.media):rowMedia(bird),father=hasFather?await resolveParent(env,owner,validateParent(input.updates.father,'父鸟',true),'MALE','父鸟',bird.id):parseJson(bird.father_snapshot_json,null),mother=hasMother?await resolveParent(env,owner,validateParent(input.updates.mother,'母鸟',true),'FEMALE','母鸟',bird.id):parseJson(bird.mother_snapshot_json,null),purchaseDate=hasPurchaseDate?validatePurchaseDate(input.updates):bird.purchase_date; ensure(!(father&&mother&&father.source==='LIBRARY'&&mother.source==='LIBRARY'&&father.id===mother.id),'VALIDATION_ERROR','父鸟和母鸟不能为同一只鸟'); const next={...bird,breed:value.breed??bird.breed,species:value.species??bird.species,ring_number:value.ringNumber??bird.ring_number,ring_number_normalized:value.ringNumberNormalized??bird.ring_number_normalized,gender:value.gender??bird.gender,birth_date:value.birthDate??bird.birth_date,purchase_date:purchaseDate,price_cents:value.priceCents??bird.price_cents,public_intro:value.publicIntro??bird.public_intro,private_notes:value.privateNotes??bird.private_notes,media_json:json(media),father_id:father&&father.id,mother_id:mother&&mother.id,father_snapshot_json:json(father),mother_snapshot_json:json(mother),revision:bird.revision+1,updated_at:nowIso()}; return {data:{id:bird.id,revision:next.revision},releasedAssetIds:value.media?removedMediaIds(rowMedia(bird),media):[],statements:[statement(env,'UPDATE parrots SET breed=?,species=?,ring_number=?,ring_number_normalized=?,gender=?,birth_date=?,purchase_date=?,price_cents=?,public_intro=?,private_notes=?,media_json=?,father_id=?,mother_id=?,father_snapshot_json=?,mother_snapshot_json=?,revision=?,updated_at=? WHERE id=?',next.breed,next.species,next.ring_number,next.ring_number_normalized,next.gender,next.birth_date,next.purchase_date,next.price_cents,next.public_intro,next.private_notes,next.media_json,next.father_id,next.mother_id,next.father_snapshot_json,next.mother_snapshot_json,next.revision,next.updated_at,bird.id),auditStatement(env,owner,'parrots.update','parrot',bird.id,requestId,bird,next)]} },
  'parrots.delete':async(env,owner,input,requestId,actorOpenId)=>{ const bird=await owned(env,'parrots',text(input.id,'id',80),owner); revisionCheck(bird,input.revision); ensure(!bird.active_pair_id,'INVALID_STATE','请先结束当前配对或孵化任务'); const children=await first(env,'SELECT id FROM parrots WHERE owner_open_id=? AND deleted_at IS NULL AND (father_id=? OR mother_id=?) LIMIT 1',owner,bird.id,bird.id); ensure(!children,'INVALID_STATE','该鸟已被子代引用，不能删除血统档案'); const deletedAt=nowIso(),purgeAt=new Date(new Date(deletedAt).getTime()+RECYCLE_WINDOW_MS).toISOString(),next={...bird,deleted_at:deletedAt,deleted_by:actorOpenId||null,revision:Number(bird.revision)+1,updated_at:deletedAt}; return {data:{id:bird.id,deleted:true,deletedAt,purgeAt},statements:[statement(env,'UPDATE parrots SET deleted_at=?,deleted_by=?,revision=?,updated_at=? WHERE id=? AND owner_open_id=?',next.deleted_at,next.deleted_by,next.revision,next.updated_at,bird.id,owner),auditStatement(env,owner,'parrots.delete','parrot',bird.id,requestId,bird,{deleted:true,deletedAt,purgeAt},actorOpenId)]} },
  'parrots.restore':async(env,owner,input,requestId,actorOpenId)=>{ const bird=await owned(env,'parrots',text(input.id,'id',80),owner,true); ensure(bird.deleted_at,'INVALID_STATE','该档案不在回收站'); const purgeAt=new Date(new Date(bird.deleted_at).getTime()+RECYCLE_WINDOW_MS); ensure(Number.isFinite(purgeAt.getTime())&&purgeAt.getTime()>Date.now(),'GONE','该档案已超过 15 天恢复期限',410); const now=nowIso(),next={...bird,deleted_at:null,deleted_by:null,revision:Number(bird.revision)+1,updated_at:now}; return {data:{id:bird.id,restored:true,revision:next.revision},statements:[statement(env,'UPDATE parrots SET deleted_at=NULL,deleted_by=NULL,revision=?,updated_at=? WHERE id=? AND owner_open_id=?',next.revision,next.updated_at,bird.id,owner),auditStatement(env,owner,'parrots.restore','parrot',bird.id,requestId,bird,{restored:true},actorOpenId)]} },
  'parrots.setBreeder':(env,owner,input,requestId)=>simpleStatus(env,owner,input,requestId,STATUS.FOR_SALE,STATUS.BREEDER,'parrots.setBreeder'),
  'parrots.unsetBreeder':async(env,owner,input,requestId)=>{ const bird=await owned(env,'parrots',text(input.id,'id',80),owner); revisionCheck(bird,input.revision); ensure(bird.status===STATUS.BREEDER,'INVALID_STATE','当前状态不允许执行该操作'); const now=nowIso(),next={...bird,status:STATUS.FOR_SALE,introduction_stage:bird.record_source==='INTRODUCTION'?'GROWING':bird.introduction_stage,revision:bird.revision+1,updated_at:now}; return {data:{id:bird.id,revision:next.revision},statements:[statement(env,'UPDATE parrots SET status=?,introduction_stage=?,revision=?,updated_at=? WHERE id=?',next.status,next.introduction_stage,next.revision,now,bird.id),auditStatement(env,owner,'parrots.unsetBreeder','parrot',bird.id,requestId,bird,next)]} },
  'parrots.setFeedingPlan':async(env,owner,input,requestId)=>{ const bird=await owned(env,'parrots',text(input.id,'id',80),owner); revisionCheck(bird,input.revision); const planId=text(input.feedingPlanId,'喂养方案',80,false); const plan=planId?await owned(env,'feeding_plans',planId,owner):null,now=nowIso(),next={...bird,feeding_plan_id:plan&&plan.id||null,revision:bird.revision+1,updated_at:now}; return {data:{id:bird.id,feedingPlanId:next.feeding_plan_id||'',revision:next.revision},statements:[statement(env,'UPDATE parrots SET feeding_plan_id=?,revision=?,updated_at=? WHERE id=?',next.feeding_plan_id,next.revision,now,bird.id),auditStatement(env,owner,'parrots.setFeedingPlan','parrot',bird.id,requestId,bird,next)]} },
  'feedingPlans.create':async(env,owner,input,requestId)=>{ const value=validateFeedingPlan(input),now=nowIso(),plan={id:id(),owner_open_id:owner,name:value.name,species:value.species,stage:value.stage,age_from_months:value.ageFromMonths,age_to_months:value.ageToMonths,formula_name:value.formulaName,water_ml:value.waterMl,powder_scoops:value.powderScoops,temperature_min:value.temperatureMin,temperature_max:value.temperatureMax,feedings_per_day:value.feedingsPerDay,amount_ml:value.amountMl,feeding_method:value.feedingMethod,temperature_check:value.temperatureCheck,preparation_notes:value.preparationNotes,feeding_notes:value.feedingNotes,fullness_notes:value.fullnessNotes,warning_notes:value.warningNotes,feeding_type:value.feedingType,seed_food_name:value.seedFoodName,seed_food_amount:value.seedFoodAmount,seed_food_notes:value.seedFoodNotes,age_from_days:value.ageFromDays,age_to_days:value.ageToDays,revision:1,created_at:now,updated_at:now,deleted_at:null}; return {data:{id:plan.id,revision:1},statements:[statement(env,'INSERT INTO feeding_plans (id,owner_open_id,name,species,stage,age_from_months,age_to_months,formula_name,water_ml,powder_scoops,temperature_min,temperature_max,feedings_per_day,amount_ml,feeding_method,temperature_check,preparation_notes,feeding_notes,fullness_notes,warning_notes,feeding_type,seed_food_name,seed_food_amount,seed_food_notes,age_from_days,age_to_days,revision,created_at,updated_at,deleted_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',...Object.values(plan)),auditStatement(env,owner,'feedingPlans.create','feedingPlan',plan.id,requestId,null,plan)]} },
  'feedingPlans.update':async(env,owner,input,requestId)=>{ const previous=await owned(env,'feeding_plans',text(input.id,'id',80),owner),value=validateFeedingPlan(input); revisionCheck(previous,input.revision); ensure(!previous.is_enabled,'INVALID_STATE','已开启方案不能编辑，请先关闭方案'); const now=nowIso(),next={...previous,name:value.name,species:value.species,stage:value.stage,age_from_months:value.ageFromMonths,age_from_days:value.ageFromDays,age_to_months:value.ageToMonths,age_to_days:value.ageToDays,formula_name:value.formulaName,water_ml:value.waterMl,powder_scoops:value.powderScoops,temperature_min:value.temperatureMin,temperature_max:value.temperatureMax,feedings_per_day:value.feedingsPerDay,amount_ml:value.amountMl,feeding_method:value.feedingMethod,temperature_check:value.temperatureCheck,preparation_notes:value.preparationNotes,feeding_notes:value.feedingNotes,fullness_notes:value.fullnessNotes,warning_notes:value.warningNotes,feeding_type:value.feedingType,seed_food_name:value.seedFoodName,seed_food_amount:value.seedFoodAmount,seed_food_notes:value.seedFoodNotes,revision:previous.revision+1,updated_at:now}; return {data:{id:previous.id,revision:next.revision},statements:[statement(env,'UPDATE feeding_plans SET name=?,species=?,stage=?,age_from_months=?,age_from_days=?,age_to_months=?,age_to_days=?,formula_name=?,water_ml=?,powder_scoops=?,temperature_min=?,temperature_max=?,feedings_per_day=?,amount_ml=?,feeding_method=?,temperature_check=?,preparation_notes=?,feeding_notes=?,fullness_notes=?,warning_notes=?,feeding_type=?,seed_food_name=?,seed_food_amount=?,seed_food_notes=?,revision=?,updated_at=? WHERE id=?',next.name,next.species,next.stage,next.age_from_months,next.age_from_days,next.age_to_months,next.age_to_days,next.formula_name,next.water_ml,next.powder_scoops,next.temperature_min,next.temperature_max,next.feedings_per_day,next.amount_ml,next.feeding_method,next.temperature_check,next.preparation_notes,next.feeding_notes,next.fullness_notes,next.warning_notes,next.feeding_type,next.seed_food_name,next.seed_food_amount,next.seed_food_notes,next.revision,now,previous.id),auditStatement(env,owner,'feedingPlans.update','feedingPlan',previous.id,requestId,previous,next)]} },
  'feedingPlans.setEnabled':async(env,owner,input,requestId)=>{ const plan=await owned(env,'feeding_plans',text(input.id,'id',80),owner); revisionCheck(plan,input.revision); const enabled=Boolean(input.enabled),now=nowIso(); if(enabled){ const start=Number(plan.age_from_months)*31+Number(plan.age_from_days||0),end=Number(plan.age_to_months)*31+Number(plan.age_to_days||0),conflict=await first(env,'SELECT name FROM feeding_plans WHERE owner_open_id=? AND deleted_at IS NULL AND is_enabled=1 AND species=? AND id<>? AND NOT ((age_to_months * 31 + age_to_days) < ? OR (age_from_months * 31 + age_from_days) > ?) LIMIT 1',owner,plan.species,plan.id,start,end); ensure(!conflict,'CONFLICT',`与已开启方案“${conflict && conflict.name}”的年龄范围冲突`,409) } const next={...plan,is_enabled:enabled?1:0,revision:plan.revision+1,updated_at:now}; return {data:{id:plan.id,isEnabled:enabled,revision:next.revision},statements:[statement(env,'UPDATE feeding_plans SET is_enabled=?,revision=?,updated_at=? WHERE id=?',next.is_enabled,next.revision,now,plan.id),auditStatement(env,owner,'feedingPlans.setEnabled','feedingPlan',plan.id,requestId,plan,next)]} },
  'feedingPlans.delete':async(env,owner,input,requestId)=>{ const plan=await owned(env,'feeding_plans',text(input.id,'id',80),owner); revisionCheck(plan,input.revision); ensure(!plan.is_enabled,'INVALID_STATE','已开启方案不能删除，请先关闭方案'); const now=nowIso(); return {data:{id:plan.id,deleted:true},statements:[statement(env,'UPDATE parrots SET feeding_plan_id=NULL,revision=revision+1,updated_at=? WHERE owner_open_id=? AND feeding_plan_id=? AND deleted_at IS NULL',now,owner,plan.id),statement(env,'DELETE FROM feeding_plans WHERE id=? AND owner_open_id=?',plan.id,owner),auditStatement(env,owner,'feedingPlans.delete','feedingPlan',plan.id,requestId,plan,{deleted:true})]} },
  'supplies.create':async(env,owner,input,requestId)=>{ const value=validateSupply(input),now=nowIso(),record={id:id(),owner_open_id:owner,category:value.category,name:value.name,amount_cents:value.amountCents,weight:value.weight,purchase_date:value.purchaseDate,notes:value.notes,created_at:now}; return {data:{id:record.id},statements:[statement(env,'INSERT INTO supply_records (id,owner_open_id,category,name,amount_cents,weight,purchase_date,notes,created_at) VALUES (?,?,?,?,?,?,?,?,?)',...Object.values(record)),auditStatement(env,owner,'supplies.create','supplyRecord',record.id,requestId,null,record)]} },
  'supplies.delete':async(env,owner,input,requestId)=>{ const record=await first(env,'SELECT * FROM supply_records WHERE id=? AND owner_open_id=?',text(input.id,'id',80),owner); ensure(record,'NOT_FOUND','记录不存在',404); return {data:{id:record.id,deleted:true},statements:[statement(env,'DELETE FROM supply_records WHERE id=? AND owner_open_id=?',record.id,owner),auditStatement(env,owner,'supplies.delete','supplyRecord',record.id,requestId,record,{deleted:true})]} },
  'breeding.pair':async(env,owner,input,requestId)=>{ const male=await owned(env,'parrots',text(input.maleId,'maleId',80),owner),female=await owned(env,'parrots',text(input.femaleId,'femaleId',80),owner); revisionCheck(male,input.maleRevision); revisionCheck(female,input.femaleRevision); ensure(male.gender==='MALE'&&female.gender==='FEMALE','INVALID_STATE','只能选择公鸟和母鸟配对'); ensure(male.status===STATUS.BREEDER&&female.status===STATUS.BREEDER,'INVALID_STATE','只有种鸟可以配对'); const pairId=id(),now=nowIso(),pair={id:pairId,owner_open_id:owner,male_id:male.id,female_id:female.id,status:'ACTIVE',paired_at:now,ended_at:null,end_reason:null,revision:1,created_at:now,updated_at:now,deleted_at:null}; return {data:{id:pairId,revision:1},statements:[statement(env,'INSERT INTO breeding_pairs (id,owner_open_id,male_id,female_id,status,paired_at,ended_at,end_reason,revision,created_at,updated_at,deleted_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)',...Object.values(pair)),statement(env,'UPDATE parrots SET status=?,active_pair_id=?,paired_at=?,revision=revision+1,updated_at=? WHERE id IN (?,?)',STATUS.PAIRED,pairId,now,now,male.id,female.id),auditStatement(env,owner,'breeding.pair','breedingPair',pairId,requestId,null,pair)]} },
  'breeding.cancel':async(env,owner,input,requestId)=>{ const pair=await owned(env,'breeding_pairs',text(input.pairId,'pairId',80),owner); revisionCheck(pair,input.revision); ensure(pair.status==='ACTIVE','INVALID_STATE','孵化中的配对不能直接拆除'); const now=nowIso(); return {data:{id:pair.id,status:'CLOSED',revision:pair.revision+1},statements:await closePair(env,owner,pair,'CANCELLED',requestId,now)} },
  'hatching.create':async(env,owner,input,requestId)=>createHatching(env,owner,input,requestId),
  'hatching.updateProgress':async(env,owner,input,requestId)=>{ const record=await owned(env,'hatching_records',text(input.id,'id',80),owner); revisionCheck(record,input.revision); ensure(record.status==='INCUBATING','INVALID_STATE','只能更新进行中的孵化任务'); const hatched=integer(input.hatched,'出壳数量',0,record.eggs),offspring=validateOffspringGroups(input.offspringGroups,hatched),now=nowIso(),next={...record,hatched,offspring_json:json(offspring===undefined?parseJson(record.offspring_json,[]):offspring),revision:record.revision+1,updated_at:now}; return {data:{id:record.id,revision:next.revision},statements:[statement(env,'UPDATE hatching_records SET hatched=?,offspring_json=?,revision=?,updated_at=? WHERE id=?',hatched,next.offspring_json,next.revision,now,record.id),auditStatement(env,owner,'hatching.updateProgress','hatchingRecord',record.id,requestId,record,next)]} },
  'hatching.complete':async(env,owner,input,requestId)=>finishHatching(env,owner,input,requestId,false),
  'hatching.delete':async(env,owner,input,requestId)=>finishHatching(env,owner,input,requestId,true),
  'sales.create':async(env,owner,input,requestId)=>{ const bird=await owned(env,'parrots',text(input.parrotId,'parrotId',80),owner); revisionCheck(bird,input.parrotRevision); ensure(bird.status===STATUS.FOR_SALE&&(bird.record_source!=='INTRODUCTION'||bird.introduction_stage==='FOR_SALE'),'INVALID_STATE','请先将引种鸟转为待售'); const buyer=text(input.buyer,'买家姓名',100),contact=text(input.buyerContact,'联系方式',200,false),saleDate=dateOnly(input.saleDate,'成交日期'),price=integer(input.priceCents,'成交金额',0,99999999900),saleId=id(),now=nowIso(),snap=snapshot(bird),sale={id:saleId,owner_open_id:owner,parrot_id:bird.id,breed:snap.breed,species:snap.species,ring_number:snap.ringNumber,gender:snap.gender,birth_date:snap.birthDate,media_json:json(snap.media),buyer,buyer_contact:contact,sale_date:saleDate,price_cents:price,status:'COMPLETED',return_reason:'',returned_at:null,follow_up_status:'WAITING',revision:1,created_at:now,updated_at:now,deleted_at:null}; return {data:{id:saleId,revision:1},statements:[statement(env,'INSERT INTO sales_records (id,owner_open_id,parrot_id,breed,species,ring_number,gender,birth_date,media_json,buyer,buyer_contact,sale_date,price_cents,status,return_reason,returned_at,follow_up_status,revision,created_at,updated_at,deleted_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',...Object.values(sale)),statement(env,'UPDATE parrots SET status=?,revision=revision+1,updated_at=? WHERE id=?',STATUS.SOLD,now,bird.id),auditStatement(env,owner,'sales.create','saleRecord',saleId,requestId,null,sale)]} },
  'sales.delete':async(env,owner,input,requestId,actorOpenId)=>{
    const sale=await owned(env,'sales_records',text(input.id,'id',80),owner)
    revisionCheck(sale,input.revision)
    ensure(sale.status==='COMPLETED','INVALID_STATE','仅支持撤销尚未退货的售出记录')
    const bird=await owned(env,'parrots',sale.parrot_id,owner,true)
    ensure(bird.status===STATUS.SOLD,'INVALID_STATE','鹦鹉状态与销售记录不一致，请刷新后重试')
    const restoredFromRecycleBin=Boolean(bird.deleted_at)
    if(restoredFromRecycleBin){
      const purgeAt=new Date(new Date(bird.deleted_at).getTime()+RECYCLE_WINDOW_MS)
      ensure(Number.isFinite(purgeAt.getTime())&&purgeAt.getTime()>Date.now(),'GONE','鹦鹉已超过 15 天回收期限，无法撤销售出',410)
    }
    const now=nowIso(),next={...sale,deleted_at:now,revision:sale.revision+1,updated_at:now},nextBird={...bird,status:STATUS.FOR_SALE,deleted_at:null,deleted_by:null,revision:Number(bird.revision)+1,updated_at:now}
    return {data:{id:sale.id,deleted:true,revision:next.revision,restoredFromRecycleBin},statements:[
      statement(env,'UPDATE sales_records SET deleted_at=?,revision=?,updated_at=? WHERE id=? AND owner_open_id=?',now,next.revision,now,sale.id,owner),
      statement(env,'UPDATE parrots SET status=?,deleted_at=NULL,deleted_by=NULL,revision=?,updated_at=? WHERE id=? AND owner_open_id=?',STATUS.FOR_SALE,nextBird.revision,now,bird.id,owner),
      auditStatement(env,owner,'sales.delete','saleRecord',sale.id,requestId,sale,next,actorOpenId),
      auditStatement(env,owner,'parrots.restoreFromSaleDelete','parrot',bird.id,requestId,bird,nextBird,actorOpenId)
    ]}
  },
  'sales.return':async(env,owner,input,requestId)=>{ const sale=await owned(env,'sales_records',text(input.id,'id',80),owner); revisionCheck(sale,input.revision); ensure(sale.status==='COMPLETED','INVALID_STATE','该交易不能重复退货'); const bird=await owned(env,'parrots',sale.parrot_id,owner); ensure(bird.status===STATUS.SOLD,'INVALID_STATE','鹦鹉状态与销售记录不一致'); const reason=text(input.reason,'退货原因',500),now=nowIso(),next={...sale,status:'RETURNED',return_reason:reason,returned_at:now,revision:sale.revision+1,updated_at:now}; return {data:{id:sale.id,revision:next.revision},statements:[statement(env,'UPDATE sales_records SET status=?,return_reason=?,returned_at=?,revision=?,updated_at=? WHERE id=?','RETURNED',reason,now,next.revision,now,sale.id),statement(env,'UPDATE parrots SET status=?,revision=revision+1,updated_at=? WHERE id=?',STATUS.RETURNED,now,bird.id),auditStatement(env,owner,'sales.return','saleRecord',sale.id,requestId,sale,next)]} },
  'sales.updateFollowUp':async(env,owner,input,requestId)=>{ const sale=await owned(env,'sales_records',text(input.id,'id',80),owner); revisionCheck(sale,input.revision); ensure(FOLLOW_UP.has(input.status),'VALIDATION_ERROR','回访状态无效'); const now=nowIso(),next={...sale,follow_up_status:input.status,revision:sale.revision+1,updated_at:now}; return {data:{id:sale.id,revision:next.revision},statements:[statement(env,'UPDATE sales_records SET follow_up_status=?,revision=?,updated_at=? WHERE id=?',input.status,next.revision,now,sale.id),auditStatement(env,owner,'sales.updateFollowUp','saleRecord',sale.id,requestId,sale,next)]} },
  'shares.create':async(env,owner,input,requestId)=>{ const bird=await owned(env,'parrots',text(input.parrotId,'parrotId',80),owner),token=await deriveShareToken(owner,requestId,env.SHARE_TOKEN_SECRET),tokenHash=await sha256(token),now=nowIso(),expiresAt=new Date(Date.now()+604800000).toISOString(); const share={token_hash:tokenHash,owner_open_id:owner,parrot_id:bird.id,expires_at:expiresAt,revoked_at:null,revision:1,created_at:now,updated_at:now,deleted_at:null}; return {data:{token,parrotId:bird.id,expiresAt},statements:[statement(env,'INSERT INTO share_tokens (token_hash,owner_open_id,parrot_id,expires_at,revoked_at,revision,created_at,updated_at,deleted_at) VALUES (?,?,?,?,?,?,?,?,?)',...Object.values(share)),auditStatement(env,owner,'shares.create','shareToken',tokenHash,requestId,null,{...share,token_hash:'[HASHED]'})]} },
  'shares.revoke':async(env,owner,input,requestId)=>{ const tokenHash=input.token?await sha256(text(input.token,'token',200)):text(input.id,'id',100); const share=await first(env,'SELECT * FROM share_tokens WHERE token_hash=? AND owner_open_id=?',tokenHash,owner); ensure(share,'NOT_FOUND','分享不存在',404); return {data:{id:tokenHash,revoked:true},statements:[statement(env,'DELETE FROM share_tokens WHERE token_hash=? AND owner_open_id=?',tokenHash,owner),auditStatement(env,owner,'shares.revoke','shareToken',tokenHash,requestId,share,{deleted:true})]} }
}

async function createFromClutch(env,owner,input,requestId){
  const record=await owned(env,'hatching_records',text(input.hatchingRecordId,'孵化记录',80),owner)
  revisionCheck(record,input.revision)
  ensure(record.status==='COMPLETED'&&record.hatched>0,'INVALID_STATE','请在孵化完成且有幼鸟出壳后再录入')
  const existing=await first(env,'SELECT id FROM parrots WHERE owner_open_id=? AND birth_hatching_record_id=? AND deleted_at IS NULL LIMIT 1',owner,record.id)
  ensure(!existing,'INVALID_STATE','本窝幼鸟已录入，不能重复创建')
  const chicks=validateClutchChicks(input.chicks,record.hatched),father=await owned(env,'parrots',record.male_id,owner),mother=await owned(env,'parrots',record.female_id,owner)
  const fatherSnapshot={source:'LIBRARY',id:father.id,species:father.species,ringNumber:father.ring_number},motherSnapshot={source:'LIBRARY',id:mother.id,species:mother.species,ringNumber:mother.ring_number}
  const birthDate=dateOnly(String(record.completed_at||record.updated_at||record.start_date).slice(0,10),'出生日期'),now=nowIso(),statements=[],created=[]
  for(const chick of chicks){
    const data={id:id(),owner_open_id:owner,breed:chick.breed,species:chick.species,ring_number:chick.ringNumber,ring_number_normalized:chick.ringNumberNormalized,gender:chick.gender,status:STATUS.FOR_SALE,birth_date:birthDate,price_cents:chick.priceCents,public_intro:'',private_notes:chick.privateNotes,media_json:'[]',father_id:father.id,mother_id:mother.id,father_snapshot_json:json(fatherSnapshot),mother_snapshot_json:json(motherSnapshot),birth_hatching_record_id:record.id,active_pair_id:null,paired_at:null,revision:1,created_at:now,updated_at:now,deleted_at:null,deleted_by:null}
    statements.push(statement(env,'INSERT INTO parrots (id,owner_open_id,breed,species,ring_number,ring_number_normalized,gender,status,birth_date,price_cents,public_intro,private_notes,media_json,father_id,mother_id,father_snapshot_json,mother_snapshot_json,birth_hatching_record_id,active_pair_id,paired_at,revision,created_at,updated_at,deleted_at,deleted_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',...Object.values(data)),auditStatement(env,owner,'parrots.createFromClutch','parrot',data.id,requestId,null,data))
    created.push(data.id)
  }
  return {data:{ids:created,birthDate},statements}
}

async function createHatching(env,owner,input,requestId){ const male=await owned(env,'parrots',text(input.maleId,'maleId',80),owner),female=await owned(env,'parrots',text(input.femaleId,'femaleId',80),owner); revisionCheck(male,input.maleRevision); revisionCheck(female,input.femaleRevision); ensure(male.gender==='MALE'&&female.gender==='FEMALE','INVALID_STATE','孵化父母必须为公鸟和母鸟'); const breeders=male.status===STATUS.BREEDER&&female.status===STATUS.BREEDER,paired=male.status===STATUS.PAIRED&&female.status===STATUS.PAIRED&&male.active_pair_id&&male.active_pair_id===female.active_pair_id; ensure(breeders||paired,'INVALID_STATE','父母鸟状态不允许启动孵化'); const duplicate=await first(env,'SELECT id FROM hatching_records WHERE owner_open_id=? AND male_id=? AND female_id=? AND status=? AND deleted_at IS NULL',owner,male.id,female.id,'INCUBATING'); ensure(!duplicate,'INVALID_STATE','该组合已有进行中的孵化任务'); const now=nowIso(),statements=[]; let pairId,pairRevision=1,pairedAt=now;if(paired){ const pair=await owned(env,'breeding_pairs',male.active_pair_id,owner); ensure(pair.status==='ACTIVE','INVALID_STATE','配对状态异常'); if(input.pairRevision!=null)revisionCheck(pair,input.pairRevision); pairId=pair.id;pairRevision=pair.revision+1;pairedAt=pair.paired_at;statements.push(statement(env,'UPDATE breeding_pairs SET status=?,revision=?,updated_at=? WHERE id=?','INCUBATING',pairRevision,now,pairId)) }else{ pairId=id();statements.push(statement(env,'INSERT INTO breeding_pairs (id,owner_open_id,male_id,female_id,status,paired_at,ended_at,end_reason,revision,created_at,updated_at,deleted_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)',pairId,owner,male.id,female.id,'INCUBATING',now,null,null,1,now,now,null)) } const recordId=id(),eggs=integer(input.eggs,'蛋数量',1,100),species=text(input.species,'品种',60),startDate=dateOnly(input.startDate,'开始日期'),record={id:recordId,owner_open_id:owner,pair_id:pairId,male_id:male.id,female_id:female.id,male_ring_number:male.ring_number,female_ring_number:female.ring_number,species,start_date:startDate,eggs,hatched:0,offspring_json:'[]',status:'INCUBATING',completed_at:null,revision:1,created_at:now,updated_at:now,deleted_at:null,deleted_by:null};statements.push(statement(env,'INSERT INTO hatching_records (id,owner_open_id,pair_id,male_id,female_id,male_ring_number,female_ring_number,species,start_date,eggs,hatched,offspring_json,status,completed_at,revision,created_at,updated_at,deleted_at,deleted_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',...Object.values(record)));statements.push(statement(env,'UPDATE parrots SET status=?,active_pair_id=?,paired_at=?,revision=revision+1,updated_at=? WHERE id IN (?,?)',STATUS.INCUBATING,pairId,pairedAt,now,male.id,female.id));statements.push(auditStatement(env,owner,'hatching.create','hatchingRecord',recordId,requestId,null,record));return {data:{id:recordId,revision:1},statements} }

async function finishHatching(env,owner,input,requestId,deleting){ const record=await owned(env,'hatching_records',text(input.id,'id',80),owner); revisionCheck(record,input.revision); const now=nowIso(),statements=[]; if(record.status==='INCUBATING'){ const pair=await owned(env,'breeding_pairs',record.pair_id,owner); ensure(pair.status==='INCUBATING','INVALID_STATE','配对状态异常'); statements.push(...await closePair(env,owner,pair,deleting?'HATCHING_CANCELLED':'HATCHING_COMPLETED',requestId,now)) }else if(!deleting)throw new ApiError('INVALID_STATE','孵化任务已经完成'); if(deleting){ const chicks=await first(env,'SELECT id FROM parrots WHERE owner_open_id=? AND birth_hatching_record_id=? AND deleted_at IS NULL LIMIT 1',owner,record.id); ensure(!chicks,'INVALID_STATE','本窝已有幼鸟档案，不能移除孵化记录'); statements.push(statement(env,'DELETE FROM hatching_records WHERE id=? AND owner_open_id=?',record.id,owner),auditStatement(env,owner,'hatching.delete','hatchingRecord',record.id,requestId,record,{deleted:true})); return {data:{id:record.id,deleted:true},statements} } const next={...record,status:'COMPLETED',completed_at:now,revision:record.revision+1,updated_at:now};statements.push(statement(env,'UPDATE hatching_records SET status=?,completed_at=?,revision=?,updated_at=? WHERE id=?','COMPLETED',now,next.revision,now,record.id));statements.push(auditStatement(env,owner,'hatching.complete','hatchingRecord',record.id,requestId,record,next));return {data:{id:record.id,revision:next.revision},statements} }

export async function executeRead(env,owner,action,input,baseUrl,sessionToken){
  if(action==='sync.snapshot'){ const [parrots,pairs,hatching,sales,dashboardData]=await Promise.all([executeRead(env,owner,'parrots.list',{},baseUrl,sessionToken),executeRead(env,owner,'breeding.listActive',{},baseUrl,sessionToken),executeRead(env,owner,'hatching.list',{},baseUrl,sessionToken),executeRead(env,owner,'sales.list',{},baseUrl,sessionToken),executeRead(env,owner,'dashboard.get',{},baseUrl,sessionToken)]); return {parrots,pairs,hatching,sales,dashboard:dashboardData} }
  if(action==='parrots.list'){ const rows=await all(env,'SELECT * FROM parrots WHERE owner_open_id=? AND deleted_at IS NULL ORDER BY created_at DESC',owner); return {items:await Promise.all(rows.map(row=>serializeParrot(env,row,env.MEDIA_SIGNING_SECRET,baseUrl,sessionToken))),nextCursor:null} }
  if(action==='parrots.recycleBin'){ const cutoff=new Date(Date.now()-RECYCLE_WINDOW_MS).toISOString(),rows=await all(env,'SELECT * FROM parrots WHERE owner_open_id=? AND deleted_at IS NOT NULL AND deleted_at>? ORDER BY deleted_at DESC',owner,cutoff); const items=await Promise.all(rows.map(async row=>({...(await serializeParrot(env,row,env.MEDIA_SIGNING_SECRET,baseUrl,sessionToken)),deletedAt:row.deleted_at,purgeAt:new Date(new Date(row.deleted_at).getTime()+RECYCLE_WINDOW_MS).toISOString()}))); return {items,nextCursor:null} }
  if(action==='parrots.get'){ return serializeParrot(env,await owned(env,'parrots',text(input.id,'id',80),owner),env.MEDIA_SIGNING_SECRET,baseUrl,sessionToken) }
  if(action==='feedingPlans.list'){ const rows=await all(env,'SELECT * FROM feeding_plans WHERE owner_open_id=? AND deleted_at IS NULL ORDER BY species,age_from_months,name',owner); return rows.map(feedingPlanView) }
  if(action==='supplies.list'){ const rows=await all(env,'SELECT * FROM supply_records WHERE owner_open_id=? ORDER BY purchase_date DESC,created_at DESC',owner); return rows.map(supplyView) }
  if(action==='breeding.listActive'){ const pairs=await all(env,"SELECT * FROM breeding_pairs WHERE owner_open_id=? AND deleted_at IS NULL AND status IN ('ACTIVE','INCUBATING') ORDER BY paired_at DESC",owner),result=[]; for(const pair of pairs){ const male=await owned(env,'parrots',pair.male_id,owner),female=await owned(env,'parrots',pair.female_id,owner); result.push({id:pair.id,maleId:pair.male_id,femaleId:pair.female_id,status:pair.status,pairedAt:pair.paired_at,revision:pair.revision,createdAt:pair.created_at,updatedAt:pair.updated_at,male:await serializeParrot(env,male,env.MEDIA_SIGNING_SECRET,baseUrl,sessionToken),female:await serializeParrot(env,female,env.MEDIA_SIGNING_SECRET,baseUrl,sessionToken)}) } return result }
  if(action==='hatching.list'){ const rows=await all(env,'SELECT h.*,p.paired_at AS pairing_date,male.species AS male_species,female.species AS female_species,(SELECT COUNT(*) FROM parrots chick WHERE chick.owner_open_id=h.owner_open_id AND chick.birth_hatching_record_id=h.id AND chick.deleted_at IS NULL) AS offspring_registered FROM hatching_records h LEFT JOIN breeding_pairs p ON p.id=h.pair_id AND p.owner_open_id=h.owner_open_id LEFT JOIN parrots male ON male.id=h.male_id AND male.owner_open_id=h.owner_open_id LEFT JOIN parrots female ON female.id=h.female_id AND female.owner_open_id=h.owner_open_id WHERE h.owner_open_id=? AND h.deleted_at IS NULL ORDER BY h.start_date DESC,h.created_at DESC',owner),items=await Promise.all(rows.map(async row=>{const offspring=await all(env,'SELECT id,ring_number FROM parrots WHERE owner_open_id=? AND birth_hatching_record_id=? AND deleted_at IS NULL ORDER BY created_at,id',owner,row.id);return{id:row.id,pairId:row.pair_id,maleId:row.male_id,femaleId:row.female_id,maleSnapshot:{species:row.male_species||row.species,ringNumber:row.male_ring_number},femaleSnapshot:{species:row.female_species||row.species,ringNumber:row.female_ring_number},pairingDate:row.pairing_date||'',species:row.species,startDate:row.start_date,eggs:row.eggs,hatched:row.hatched,offspringGroups:parseJson(row.offspring_json,[]),offspring:offspring.map(chick=>({id:chick.id,ringNumber:chick.ring_number||''})),status:row.status,revision:row.revision,completedAt:row.completed_at||'',offspringRegistered:Number(row.offspring_registered||0),createdAt:row.created_at,updatedAt:row.updated_at}})); return {items,nextCursor:null} }
  if(action==='sales.list'){ const rows=await all(env,'SELECT * FROM sales_records WHERE owner_open_id=? AND deleted_at IS NULL ORDER BY sale_date DESC,created_at DESC',owner),items=[]; for(const row of rows){items.push({id:row.id,parrotId:row.parrot_id,parrotSnapshot:{breed:row.breed||'',species:row.species,ringNumber:row.ring_number,gender:row.gender,birthDate:row.birth_date,media:await mediaItems(env,parseJson(row.media_json,[]),env.MEDIA_SIGNING_SECRET,baseUrl,sessionToken)},buyer:row.buyer,buyerContact:row.buyer_contact,saleDate:row.sale_date,priceCents:row.price_cents,status:row.status,returnReason:row.return_reason,followUpStatus:row.follow_up_status,revision:row.revision,createdAt:row.created_at})} return {items,nextCursor:null} }
  if(action==='shares.list')return (await all(env,'SELECT token_hash AS id,parrot_id AS parrotId,expires_at AS expiresAt,revoked_at AS revokedAt,created_at AS createdAt FROM share_tokens WHERE owner_open_id=? AND deleted_at IS NULL ORDER BY created_at DESC',owner))
  if(action==='ai.saleCopy.generate')return generateSaleCopy(env,owner,input||{})
  if(action==='dashboard.get')return dashboard(env,owner)
  throw new ApiError('NOT_FOUND','接口不存在',404)
}

async function dashboard(env,owner){ const parrots=await all(env,'SELECT status,species,record_source,introduction_stage FROM parrots WHERE owner_open_id=? AND deleted_at IS NULL',owner),sales=await all(env,'SELECT status,price_cents,sale_date FROM sales_records WHERE owner_open_id=? AND deleted_at IS NULL',owner),stats={total:parrots.length,forSale:0,sold:0,returned:0,breeder:0,paired:0,incubating:0,revenueCents:0,salesTotal:sales.length,returnRate:0};const keys={FOR_SALE:'forSale',SOLD:'sold',RETURNED:'returned',BREEDER:'breeder',PAIRED:'paired',INCUBATING:'incubating'};parrots.forEach(item=>{if(item.status==='FOR_SALE'&&item.record_source==='INTRODUCTION'&&item.introduction_stage!=='FOR_SALE')return;if(keys[item.status])stats[keys[item.status]]++});const valid=sales.filter(item=>item.status==='COMPLETED');stats.revenueCents=valid.reduce((sum,item)=>sum+item.price_cents,0);stats.returnRate=sales.length?Math.round(sales.filter(item=>item.status==='RETURNED').length/sales.length*100):0;const mix={};parrots.forEach(item=>mix[item.species]=(mix[item.species]||0)+1);const species=Object.entries(mix).map(([name,count])=>({name,count,percent:parrots.length?Math.round(count/parrots.length*100):0})).sort((a,b)=>b.count-a.count).slice(0,5);const now=new Date(),trend=[];for(let offset=5;offset>=0;offset--){const date=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()-offset,1)),month=`${date.getUTCFullYear()}-${String(date.getUTCMonth()+1).padStart(2,'0')}`,monthSales=valid.filter(item=>item.sale_date.startsWith(month));trend.push({month,revenueCents:monthSales.reduce((sum,item)=>sum+item.price_cents,0),volume:monthSales.length})}return {stats,species,trend} }
