import { ApiError, STATUS, WRITE_ACTIONS, dateOnly, deriveShareToken, ensure, id, integer, json, normalizeRing, nowIso, parseJson, sha256, text } from './core.js'
import { all, auditStatement, first, mediaItems, owned, revisionCheck, rowMedia, serializeParrot, snapshot, statement } from './db.js'
import { r2AbortMultipartUpload as cosAbortMultipartUpload, r2DeleteObject as cosDeleteObject } from './r2.js'

const GENDERS = new Set(['MALE','FEMALE','UNKNOWN'])
const FOLLOW_UP = new Set(['WAITING','VISITED','UNREACHABLE'])

function validateParrot(input, partial = false) {
  const result = {}; const has = key => Object.prototype.hasOwnProperty.call(input || {}, key)
  if (!partial || has('species')) result.species = text(input.species,'品种',60)
  if (!partial || has('ringNumber')) { result.ringNumber=text(input.ringNumber,'圈号',40); result.ringNumberNormalized=normalizeRing(result.ringNumber); ensure(result.ringNumberNormalized,'VALIDATION_ERROR','圈号无效') }
  if (!partial || has('gender')) { ensure(GENDERS.has(input.gender),'VALIDATION_ERROR','性别无效'); result.gender=input.gender }
  if (!partial || has('birthDate')) { result.birthDate=dateOnly(input.birthDate,'出生日期'); const sh=new Date(Date.now()+28800000); const today=`${sh.getUTCFullYear()}-${String(sh.getUTCMonth()+1).padStart(2,'0')}-${String(sh.getUTCDate()).padStart(2,'0')}`; ensure(result.birthDate<=today,'VALIDATION_ERROR','出生日期不能晚于今天') }
  if (!partial || has('priceCents')) result.priceCents=integer(input.priceCents,'价格',0,99999999900)
  if (!partial || has('publicIntro')) result.publicIntro=text(input.publicIntro,'公开介绍',1000,false)
  if (!partial || has('privateNotes')) result.privateNotes=text(input.privateNotes,'内部备注',3000,false)
  if (!partial || has('media')) { ensure(Array.isArray(input.media)&&input.media.length<=20,'VALIDATION_ERROR','媒体数量无效'); result.media=input.media.map(item=>({assetId:text(item.assetId,'媒体标识',80),type:item.type})) }
  return result
}

async function validateMedia(env, owner, items) {
  const output=[]; const seen=new Set()
  for(const item of items||[]){ ensure(['image','video'].includes(item.type),'VALIDATION_ERROR','媒体类型无效'); ensure(!seen.has(item.assetId),'VALIDATION_ERROR','媒体不能重复'); seen.add(item.assetId); const asset=await first(env,'SELECT * FROM media_assets WHERE id=? AND owner_open_id=? AND status=? AND deleted_at IS NULL',item.assetId,owner,'COMMITTED'); ensure(asset&&asset.type===item.type,'VALIDATION_ERROR','媒体尚未完成上传'); output.push({assetId:asset.id,type:asset.type,key:asset.object_key}) }
  return output
}

async function receipt(env, owner, requestId) { return first(env,'SELECT * FROM command_receipts WHERE receipt_id=?',await sha256(`${owner}:${requestId}`)) }
function receiptResult(row) { return parseJson(row.result_json,{}) }

async function saveBatch(env, owner, action, requestId, statements, result) {
  const receiptId=await sha256(`${owner}:${requestId}`)
  statements.push(statement(env,'INSERT INTO command_receipts (receipt_id,owner_open_id,request_id,action,result_json,created_at) VALUES (?,?,?,?,?,?)',receiptId,owner,requestId,action,json(action==='shares.create'?{parrotId:result.parrotId,expiresAt:result.expiresAt}:result),nowIso()))
  try { await env.DB.batch(statements) } catch(error) { const message=String(error&&error.message||''); if(['parrots.create','parrots.update'].includes(action)&&/unique|parrots_owner_ring/i.test(message)) throw new ApiError('DUPLICATE_RING','圈号已存在',409); throw error }
  return result
}

export async function executeCommand(env, owner, action, input, requestId) {
  ensure(WRITE_ACTIONS.has(action),'NOT_FOUND','接口不存在',404); text(requestId,'requestId',100)
  const existing=await receipt(env,owner,requestId)
  if(existing){ ensure(existing.action===action,'CONFLICT','请求号已用于其他操作',409); const stored=receiptResult(existing); if(action==='shares.create') return {...stored,token:await deriveShareToken(owner,requestId,env.SHARE_TOKEN_SECRET)}; return stored }
  const result=await commandHandlers[action](env,owner,input||{},requestId)
  const data=await saveBatch(env,owner,action,requestId,result.statements,result.data)
  await purgeReleasedMedia(env,owner,result.releasedAssetIds)
  return data
}

function mediaIds(items){ return [...new Set((items||[]).map(item=>item&&item.assetId).filter(Boolean))] }
function removedMediaIds(before,after){ const next=new Set(mediaIds(after)); return mediaIds(before).filter(assetId=>!next.has(assetId)) }
async function purgeReleasedMedia(env,owner,assetIds=[]){
  for(const assetId of new Set(assetIds)){
    const asset=await first(env,'SELECT * FROM media_assets WHERE id=? AND owner_open_id=?',assetId,owner)
    if(!asset)continue
    const referenced=await first(env,"SELECT 1 AS found FROM parrots,json_each(parrots.media_json) WHERE parrots.owner_open_id=? AND json_extract(json_each.value,'$.assetId')=? UNION ALL SELECT 1 AS found FROM sales_records,json_each(sales_records.media_json) WHERE sales_records.owner_open_id=? AND json_extract(json_each.value,'$.assetId')=? LIMIT 1",owner,assetId,owner,assetId)
    if(referenced)continue
    try{
      if(asset.status==='PENDING'&&asset.upload_id)await cosAbortMultipartUpload(env,asset.object_key,asset.upload_id)
      else await cosDeleteObject(env,asset.object_key)
      await env.DB.prepare('DELETE FROM media_assets WHERE id=? AND owner_open_id=?').bind(assetId,owner).run()
    }catch(error){ console.error('[media purge]',assetId,error) }
  }
}

async function simpleStatus(env,owner,input,requestId,from,to,action){ const bird=await owned(env,'parrots',text(input.id,'id',80),owner); revisionCheck(bird,input.revision); ensure(bird.status===from,'INVALID_STATE','当前状态不允许执行该操作'); const now=nowIso(),next={...bird,status:to,revision:bird.revision+1,updated_at:now}; return {data:{id:bird.id,revision:next.revision},statements:[statement(env,'UPDATE parrots SET status=?,revision=?,updated_at=? WHERE id=?',to,next.revision,now,bird.id),auditStatement(env,owner,action,'parrot',bird.id,requestId,bird,next)]} }

async function closePair(env,owner,pair,reason,requestId,now){ const male=await owned(env,'parrots',pair.male_id,owner),female=await owned(env,'parrots',pair.female_id,owner); return [statement(env,'UPDATE breeding_pairs SET status=?,ended_at=?,end_reason=?,revision=revision+1,updated_at=? WHERE id=?','CLOSED',now,reason,now,pair.id),statement(env,'UPDATE parrots SET status=?,active_pair_id=NULL,paired_at=NULL,revision=revision+1,updated_at=? WHERE id IN (?,?)',STATUS.BREEDER,now,male.id,female.id),auditStatement(env,owner,`breeding.${reason.toLowerCase()}`,'breedingPair',pair.id,requestId,pair,{status:'CLOSED',endReason:reason})] }

const commandHandlers={
  'parrots.create':async(env,owner,input,requestId)=>{ const value=validateParrot(input),media=await validateMedia(env,owner,value.media),now=nowIso(),birdId=id(); const data={id:birdId,owner_open_id:owner,species:value.species,ring_number:value.ringNumber,ring_number_normalized:value.ringNumberNormalized,gender:value.gender,status:STATUS.FOR_SALE,birth_date:value.birthDate,price_cents:value.priceCents,public_intro:value.publicIntro,private_notes:value.privateNotes,media_json:json(media),active_pair_id:null,paired_at:null,revision:1,created_at:now,updated_at:now,deleted_at:null,deleted_by:null}; return {data:{id:birdId,revision:1},statements:[statement(env,'INSERT INTO parrots (id,owner_open_id,species,ring_number,ring_number_normalized,gender,status,birth_date,price_cents,public_intro,private_notes,media_json,active_pair_id,paired_at,revision,created_at,updated_at,deleted_at,deleted_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',...Object.values(data)),auditStatement(env,owner,'parrots.create','parrot',birdId,requestId,null,data)]} },
  'parrots.update':async(env,owner,input,requestId)=>{ const bird=await owned(env,'parrots',text(input.id,'id',80),owner); revisionCheck(bird,input.revision); const value=validateParrot(input.updates||{},true); ensure(Object.keys(value).length,'VALIDATION_ERROR','没有可更新的字段'); if(value.gender&&value.gender!==bird.gender&&bird.active_pair_id)throw new ApiError('INVALID_STATE','活动配对期间不能修改性别'); const media=value.media?await validateMedia(env,owner,value.media):rowMedia(bird); const next={...bird,species:value.species??bird.species,ring_number:value.ringNumber??bird.ring_number,ring_number_normalized:value.ringNumberNormalized??bird.ring_number_normalized,gender:value.gender??bird.gender,birth_date:value.birthDate??bird.birth_date,price_cents:value.priceCents??bird.price_cents,public_intro:value.publicIntro??bird.public_intro,private_notes:value.privateNotes??bird.private_notes,media_json:json(media),revision:bird.revision+1,updated_at:nowIso()}; return {data:{id:bird.id,revision:next.revision},releasedAssetIds:value.media?removedMediaIds(rowMedia(bird),media):[],statements:[statement(env,'UPDATE parrots SET species=?,ring_number=?,ring_number_normalized=?,gender=?,birth_date=?,price_cents=?,public_intro=?,private_notes=?,media_json=?,revision=?,updated_at=? WHERE id=?',next.species,next.ring_number,next.ring_number_normalized,next.gender,next.birth_date,next.price_cents,next.public_intro,next.private_notes,next.media_json,next.revision,next.updated_at,bird.id),auditStatement(env,owner,'parrots.update','parrot',bird.id,requestId,bird,next)]} },
  'parrots.delete':async(env,owner,input,requestId)=>{ const bird=await owned(env,'parrots',text(input.id,'id',80),owner); revisionCheck(bird,input.revision); ensure(!bird.active_pair_id,'INVALID_STATE','请先结束当前配对或孵化任务'); const sales=await all(env,'SELECT media_json FROM sales_records WHERE owner_open_id=? AND parrot_id=?',owner,bird.id),releasedAssetIds=[...mediaIds(rowMedia(bird)),...sales.flatMap(row=>mediaIds(rowMedia(row)))],statements=[statement(env,'DELETE FROM share_tokens WHERE owner_open_id=? AND parrot_id=?',owner,bird.id),statement(env,'DELETE FROM hatching_records WHERE owner_open_id=? AND (male_id=? OR female_id=?)',owner,bird.id,bird.id),statement(env,'DELETE FROM breeding_pairs WHERE owner_open_id=? AND (male_id=? OR female_id=?)',owner,bird.id,bird.id),statement(env,'DELETE FROM sales_records WHERE owner_open_id=? AND parrot_id=?',owner,bird.id),statement(env,'DELETE FROM parrots WHERE id=? AND owner_open_id=?',bird.id,owner),auditStatement(env,owner,'parrots.delete','parrot',bird.id,requestId,bird,{deleted:true})]; return {data:{id:bird.id,deleted:true},releasedAssetIds,statements} },
  'parrots.setBreeder':(env,owner,input,requestId)=>simpleStatus(env,owner,input,requestId,STATUS.FOR_SALE,STATUS.BREEDER,'parrots.setBreeder'),
  'parrots.unsetBreeder':(env,owner,input,requestId)=>simpleStatus(env,owner,input,requestId,STATUS.BREEDER,STATUS.FOR_SALE,'parrots.unsetBreeder'),
  'breeding.pair':async(env,owner,input,requestId)=>{ const male=await owned(env,'parrots',text(input.maleId,'maleId',80),owner),female=await owned(env,'parrots',text(input.femaleId,'femaleId',80),owner); revisionCheck(male,input.maleRevision); revisionCheck(female,input.femaleRevision); ensure(male.gender==='MALE'&&female.gender==='FEMALE','INVALID_STATE','只能选择公鸟和母鸟配对'); ensure(male.status===STATUS.BREEDER&&female.status===STATUS.BREEDER,'INVALID_STATE','只有种鸟可以配对'); const pairId=id(),now=nowIso(),pair={id:pairId,owner_open_id:owner,male_id:male.id,female_id:female.id,status:'ACTIVE',paired_at:now,ended_at:null,end_reason:null,revision:1,created_at:now,updated_at:now,deleted_at:null}; return {data:{id:pairId,revision:1},statements:[statement(env,'INSERT INTO breeding_pairs (id,owner_open_id,male_id,female_id,status,paired_at,ended_at,end_reason,revision,created_at,updated_at,deleted_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)',...Object.values(pair)),statement(env,'UPDATE parrots SET status=?,active_pair_id=?,paired_at=?,revision=revision+1,updated_at=? WHERE id IN (?,?)',STATUS.PAIRED,pairId,now,now,male.id,female.id),auditStatement(env,owner,'breeding.pair','breedingPair',pairId,requestId,null,pair)]} },
  'breeding.cancel':async(env,owner,input,requestId)=>{ const pair=await owned(env,'breeding_pairs',text(input.pairId,'pairId',80),owner); revisionCheck(pair,input.revision); ensure(pair.status==='ACTIVE','INVALID_STATE','孵化中的配对不能直接拆除'); const now=nowIso(); return {data:{id:pair.id,status:'CLOSED',revision:pair.revision+1},statements:await closePair(env,owner,pair,'CANCELLED',requestId,now)} },
  'hatching.create':async(env,owner,input,requestId)=>createHatching(env,owner,input,requestId),
  'hatching.updateProgress':async(env,owner,input,requestId)=>{ const record=await owned(env,'hatching_records',text(input.id,'id',80),owner); revisionCheck(record,input.revision); ensure(record.status==='INCUBATING','INVALID_STATE','只能更新进行中的孵化任务'); const hatched=integer(input.hatched,'出壳数量',0,record.eggs),now=nowIso(),next={...record,hatched,revision:record.revision+1,updated_at:now}; return {data:{id:record.id,revision:next.revision},statements:[statement(env,'UPDATE hatching_records SET hatched=?,revision=?,updated_at=? WHERE id=?',hatched,next.revision,now,record.id),auditStatement(env,owner,'hatching.updateProgress','hatchingRecord',record.id,requestId,record,next)]} },
  'hatching.complete':async(env,owner,input,requestId)=>finishHatching(env,owner,input,requestId,false),
  'hatching.delete':async(env,owner,input,requestId)=>finishHatching(env,owner,input,requestId,true),
  'sales.create':async(env,owner,input,requestId)=>{ const bird=await owned(env,'parrots',text(input.parrotId,'parrotId',80),owner); revisionCheck(bird,input.parrotRevision); ensure(bird.status===STATUS.FOR_SALE,'INVALID_STATE','只有待售档案可以确认售出'); const buyer=text(input.buyer,'买家姓名',100),contact=text(input.buyerContact,'联系方式',200,false),saleDate=dateOnly(input.saleDate,'成交日期'),price=integer(input.priceCents,'成交金额',0,99999999900),saleId=id(),now=nowIso(),snap=snapshot(bird),sale={id:saleId,owner_open_id:owner,parrot_id:bird.id,species:snap.species,ring_number:snap.ringNumber,gender:snap.gender,birth_date:snap.birthDate,media_json:json(snap.media),buyer,buyer_contact:contact,sale_date:saleDate,price_cents:price,status:'COMPLETED',return_reason:'',returned_at:null,follow_up_status:'WAITING',revision:1,created_at:now,updated_at:now,deleted_at:null}; return {data:{id:saleId,revision:1},statements:[statement(env,'INSERT INTO sales_records (id,owner_open_id,parrot_id,species,ring_number,gender,birth_date,media_json,buyer,buyer_contact,sale_date,price_cents,status,return_reason,returned_at,follow_up_status,revision,created_at,updated_at,deleted_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',...Object.values(sale)),statement(env,'UPDATE parrots SET status=?,revision=revision+1,updated_at=? WHERE id=?',STATUS.SOLD,now,bird.id),auditStatement(env,owner,'sales.create','saleRecord',saleId,requestId,null,sale)]} },
  'sales.return':async(env,owner,input,requestId)=>{ const sale=await owned(env,'sales_records',text(input.id,'id',80),owner); revisionCheck(sale,input.revision); ensure(sale.status==='COMPLETED','INVALID_STATE','该交易不能重复退货'); const bird=await owned(env,'parrots',sale.parrot_id,owner); ensure(bird.status===STATUS.SOLD,'INVALID_STATE','鹦鹉状态与销售记录不一致'); const reason=text(input.reason,'退货原因',500),now=nowIso(),next={...sale,status:'RETURNED',return_reason:reason,returned_at:now,revision:sale.revision+1,updated_at:now}; return {data:{id:sale.id,revision:next.revision},statements:[statement(env,'UPDATE sales_records SET status=?,return_reason=?,returned_at=?,revision=?,updated_at=? WHERE id=?','RETURNED',reason,now,next.revision,now,sale.id),statement(env,'UPDATE parrots SET status=?,revision=revision+1,updated_at=? WHERE id=?',STATUS.RETURNED,now,bird.id),auditStatement(env,owner,'sales.return','saleRecord',sale.id,requestId,sale,next)]} },
  'sales.updateFollowUp':async(env,owner,input,requestId)=>{ const sale=await owned(env,'sales_records',text(input.id,'id',80),owner); revisionCheck(sale,input.revision); ensure(FOLLOW_UP.has(input.status),'VALIDATION_ERROR','回访状态无效'); const now=nowIso(),next={...sale,follow_up_status:input.status,revision:sale.revision+1,updated_at:now}; return {data:{id:sale.id,revision:next.revision},statements:[statement(env,'UPDATE sales_records SET follow_up_status=?,revision=?,updated_at=? WHERE id=?',input.status,next.revision,now,sale.id),auditStatement(env,owner,'sales.updateFollowUp','saleRecord',sale.id,requestId,sale,next)]} },
  'shares.create':async(env,owner,input,requestId)=>{ const bird=await owned(env,'parrots',text(input.parrotId,'parrotId',80),owner),token=await deriveShareToken(owner,requestId,env.SHARE_TOKEN_SECRET),tokenHash=await sha256(token),now=nowIso(),expiresAt=new Date(Date.now()+604800000).toISOString(); const share={token_hash:tokenHash,owner_open_id:owner,parrot_id:bird.id,expires_at:expiresAt,revoked_at:null,revision:1,created_at:now,updated_at:now,deleted_at:null}; return {data:{token,parrotId:bird.id,expiresAt},statements:[statement(env,'INSERT INTO share_tokens (token_hash,owner_open_id,parrot_id,expires_at,revoked_at,revision,created_at,updated_at,deleted_at) VALUES (?,?,?,?,?,?,?,?,?)',...Object.values(share)),auditStatement(env,owner,'shares.create','shareToken',tokenHash,requestId,null,{...share,token_hash:'[HASHED]'})]} },
  'shares.revoke':async(env,owner,input,requestId)=>{ const tokenHash=input.token?await sha256(text(input.token,'token',200)):text(input.id,'id',100); const share=await first(env,'SELECT * FROM share_tokens WHERE token_hash=? AND owner_open_id=?',tokenHash,owner); ensure(share,'NOT_FOUND','分享不存在',404); return {data:{id:tokenHash,revoked:true},statements:[statement(env,'DELETE FROM share_tokens WHERE token_hash=? AND owner_open_id=?',tokenHash,owner),auditStatement(env,owner,'shares.revoke','shareToken',tokenHash,requestId,share,{deleted:true})]} }
}

async function createHatching(env,owner,input,requestId){ const male=await owned(env,'parrots',text(input.maleId,'maleId',80),owner),female=await owned(env,'parrots',text(input.femaleId,'femaleId',80),owner); revisionCheck(male,input.maleRevision); revisionCheck(female,input.femaleRevision); ensure(male.gender==='MALE'&&female.gender==='FEMALE','INVALID_STATE','孵化父母必须为公鸟和母鸟'); const breeders=male.status===STATUS.BREEDER&&female.status===STATUS.BREEDER,paired=male.status===STATUS.PAIRED&&female.status===STATUS.PAIRED&&male.active_pair_id&&male.active_pair_id===female.active_pair_id; ensure(breeders||paired,'INVALID_STATE','父母鸟状态不允许启动孵化'); const duplicate=await first(env,'SELECT id FROM hatching_records WHERE owner_open_id=? AND male_id=? AND female_id=? AND status=? AND deleted_at IS NULL',owner,male.id,female.id,'INCUBATING'); ensure(!duplicate,'INVALID_STATE','该组合已有进行中的孵化任务'); const now=nowIso(),statements=[]; let pairId,pairRevision=1,pairedAt=now;if(paired){ const pair=await owned(env,'breeding_pairs',male.active_pair_id,owner); ensure(pair.status==='ACTIVE','INVALID_STATE','配对状态异常'); if(input.pairRevision!=null)revisionCheck(pair,input.pairRevision); pairId=pair.id;pairRevision=pair.revision+1;pairedAt=pair.paired_at;statements.push(statement(env,'UPDATE breeding_pairs SET status=?,revision=?,updated_at=? WHERE id=?','INCUBATING',pairRevision,now,pairId)) }else{ pairId=id();statements.push(statement(env,'INSERT INTO breeding_pairs (id,owner_open_id,male_id,female_id,status,paired_at,ended_at,end_reason,revision,created_at,updated_at,deleted_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)',pairId,owner,male.id,female.id,'INCUBATING',now,null,null,1,now,now,null)) } const recordId=id(),eggs=integer(input.eggs,'蛋数量',1,100),species=text(input.species,'品种',60),startDate=dateOnly(input.startDate,'开始日期'),record={id:recordId,owner_open_id:owner,pair_id:pairId,male_id:male.id,female_id:female.id,male_ring_number:male.ring_number,female_ring_number:female.ring_number,species,start_date:startDate,eggs,hatched:0,status:'INCUBATING',completed_at:null,revision:1,created_at:now,updated_at:now,deleted_at:null,deleted_by:null};statements.push(statement(env,'INSERT INTO hatching_records (id,owner_open_id,pair_id,male_id,female_id,male_ring_number,female_ring_number,species,start_date,eggs,hatched,status,completed_at,revision,created_at,updated_at,deleted_at,deleted_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',...Object.values(record)));statements.push(statement(env,'UPDATE parrots SET status=?,active_pair_id=?,paired_at=?,revision=revision+1,updated_at=? WHERE id IN (?,?)',STATUS.INCUBATING,pairId,pairedAt,now,male.id,female.id));statements.push(auditStatement(env,owner,'hatching.create','hatchingRecord',recordId,requestId,null,record));return {data:{id:recordId,revision:1},statements} }

async function finishHatching(env,owner,input,requestId,deleting){ const record=await owned(env,'hatching_records',text(input.id,'id',80),owner); revisionCheck(record,input.revision); const now=nowIso(),statements=[]; if(record.status==='INCUBATING'){ const pair=await owned(env,'breeding_pairs',record.pair_id,owner); ensure(pair.status==='INCUBATING','INVALID_STATE','配对状态与孵化任务不一致'); statements.push(...await closePair(env,owner,pair,deleting?'HATCHING_CANCELLED':'HATCHING_COMPLETED',requestId,now)) }else if(!deleting)throw new ApiError('INVALID_STATE','孵化任务已经完成'); if(deleting){ statements.push(statement(env,'DELETE FROM hatching_records WHERE id=? AND owner_open_id=?',record.id,owner),auditStatement(env,owner,'hatching.delete','hatchingRecord',record.id,requestId,record,{deleted:true})); return {data:{id:record.id,deleted:true},statements} } const next={...record,status:'COMPLETED',completed_at:now,revision:record.revision+1,updated_at:now};statements.push(statement(env,'UPDATE hatching_records SET status=?,completed_at=?,revision=?,updated_at=? WHERE id=?','COMPLETED',now,next.revision,now,record.id));statements.push(auditStatement(env,owner,'hatching.complete','hatchingRecord',record.id,requestId,record,next));return {data:{id:record.id,revision:next.revision},statements} }

export async function executeRead(env,owner,action,input,baseUrl,sessionToken){
  if(action==='sync.snapshot'){ const [parrots,pairs,hatching,sales,dashboardData]=await Promise.all([executeRead(env,owner,'parrots.list',{},baseUrl,sessionToken),executeRead(env,owner,'breeding.listActive',{},baseUrl,sessionToken),executeRead(env,owner,'hatching.list',{},baseUrl,sessionToken),executeRead(env,owner,'sales.list',{},baseUrl,sessionToken),executeRead(env,owner,'dashboard.get',{},baseUrl,sessionToken)]); return {parrots,pairs,hatching,sales,dashboard:dashboardData} }
  if(action==='parrots.list'){ const rows=await all(env,'SELECT * FROM parrots WHERE owner_open_id=? AND deleted_at IS NULL ORDER BY created_at DESC',owner); return {items:await Promise.all(rows.map(row=>serializeParrot(env,row,env.MEDIA_SIGNING_SECRET,baseUrl,sessionToken))),nextCursor:null} }
  if(action==='parrots.get'){ return serializeParrot(env,await owned(env,'parrots',text(input.id,'id',80),owner),env.MEDIA_SIGNING_SECRET,baseUrl,sessionToken) }
  if(action==='breeding.listActive'){ const pairs=await all(env,"SELECT * FROM breeding_pairs WHERE owner_open_id=? AND deleted_at IS NULL AND status IN ('ACTIVE','INCUBATING') ORDER BY paired_at DESC",owner),result=[]; for(const pair of pairs){ const male=await owned(env,'parrots',pair.male_id,owner),female=await owned(env,'parrots',pair.female_id,owner); result.push({id:pair.id,maleId:pair.male_id,femaleId:pair.female_id,status:pair.status,pairedAt:pair.paired_at,revision:pair.revision,createdAt:pair.created_at,updatedAt:pair.updated_at,male:await serializeParrot(env,male,env.MEDIA_SIGNING_SECRET,baseUrl,sessionToken),female:await serializeParrot(env,female,env.MEDIA_SIGNING_SECRET,baseUrl,sessionToken)}) } return result }
  if(action==='hatching.list'){ const rows=await all(env,'SELECT * FROM hatching_records WHERE owner_open_id=? AND deleted_at IS NULL ORDER BY start_date DESC,created_at DESC',owner); return {items:rows.map(row=>({id:row.id,pairId:row.pair_id,maleId:row.male_id,femaleId:row.female_id,maleSnapshot:{ringNumber:row.male_ring_number},femaleSnapshot:{ringNumber:row.female_ring_number},species:row.species,startDate:row.start_date,eggs:row.eggs,hatched:row.hatched,status:row.status,revision:row.revision,createdAt:row.created_at,updatedAt:row.updated_at})),nextCursor:null} }
  if(action==='sales.list'){ const rows=await all(env,'SELECT * FROM sales_records WHERE owner_open_id=? AND deleted_at IS NULL ORDER BY sale_date DESC,created_at DESC',owner),items=[]; for(const row of rows){items.push({id:row.id,parrotId:row.parrot_id,parrotSnapshot:{species:row.species,ringNumber:row.ring_number,gender:row.gender,birthDate:row.birth_date,media:await mediaItems(env,parseJson(row.media_json,[]),env.MEDIA_SIGNING_SECRET,baseUrl,sessionToken)},buyer:row.buyer,buyerContact:row.buyer_contact,saleDate:row.sale_date,priceCents:row.price_cents,status:row.status,returnReason:row.return_reason,followUpStatus:row.follow_up_status,revision:row.revision,createdAt:row.created_at})} return {items,nextCursor:null} }
  if(action==='shares.list')return (await all(env,'SELECT token_hash AS id,parrot_id AS parrotId,expires_at AS expiresAt,revoked_at AS revokedAt,created_at AS createdAt FROM share_tokens WHERE owner_open_id=? AND deleted_at IS NULL ORDER BY created_at DESC',owner))
  if(action==='dashboard.get')return dashboard(env,owner)
  throw new ApiError('NOT_FOUND','接口不存在',404)
}

async function dashboard(env,owner){ const parrots=await all(env,'SELECT status,species FROM parrots WHERE owner_open_id=? AND deleted_at IS NULL',owner),sales=await all(env,'SELECT status,price_cents,sale_date FROM sales_records WHERE owner_open_id=? AND deleted_at IS NULL',owner),stats={total:parrots.length,forSale:0,sold:0,returned:0,breeder:0,paired:0,incubating:0,revenueCents:0,salesTotal:sales.length,returnRate:0};const keys={FOR_SALE:'forSale',SOLD:'sold',RETURNED:'returned',BREEDER:'breeder',PAIRED:'paired',INCUBATING:'incubating'};parrots.forEach(item=>{if(keys[item.status])stats[keys[item.status]]++});const valid=sales.filter(item=>item.status==='COMPLETED');stats.revenueCents=valid.reduce((sum,item)=>sum+item.price_cents,0);stats.returnRate=sales.length?Math.round(sales.filter(item=>item.status==='RETURNED').length/sales.length*100):0;const mix={};parrots.forEach(item=>mix[item.species]=(mix[item.species]||0)+1);const species=Object.entries(mix).map(([name,count])=>({name,count,percent:parrots.length?Math.round(count/parrots.length*100):0})).sort((a,b)=>b.count-a.count).slice(0,5);const now=new Date(),trend=[];for(let offset=5;offset>=0;offset--){const date=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()-offset,1)),month=`${date.getUTCFullYear()}-${String(date.getUTCMonth()+1).padStart(2,'0')}`,monthSales=valid.filter(item=>item.sale_date.startsWith(month));trend.push({month,revenueCents:monthSales.reduce((sum,item)=>sum+item.price_cents,0),volume:monthSales.length})}return {stats,species,trend} }
